// Larose Christian Academy — ORIGINAL Curriculum, Grade 6 (part 2c)
// Same 6-subject structure. Etymology explicit in Spelling & Word Origins.

import type { GradeCurriculum } from './curriculum'

const g = (
  grade: string,
  gradeNum: number,
  age: string,
  tagline: string,
  subjects: any
): GradeCurriculum => ({ grade, gradeNum, age, tagline, subjects })

// ====================== 6TH GRADE ======================
export const G6: GradeCurriculum = g('6th Grade', 6, '11-12', 'Bridge to middle school — independence.',
  [
    { name: 'Mathematics', units: [
      { name: 'Q1 — Ratios & Rates', lessons: [
        { title: 'Ratios', summary: 'Ratios are a fun way to compare two amounts by showing how much of one thing there is compared to another thing! Think of it like this: if you have 3 red apples and 2 green apples, the ratio of red to green is 3 to 2, which we can write as 3:2. Ratios help us see relationships between numbers in cooking recipes, sports scores, or even mixing paint colors. Try this activity: look around your classroom and create ratios by comparing different objects, like the number of windows to doors, or boys to girls, then share your discoveries with a partner to see who found the most interesting ratio comp' },
        { title: 'Unit Rates', summary: 'A unit rate is a special kind of rate where the second number is always 1, making it super easy to compare different things! For example, if you can run 12 miles in 3 hours, your unit rate would be 4 miles per 1 hour, or simply 4 miles per hour. Unit rates help us figure out which deals are better at the store or who runs fastest on the track team. Try this fun activity: look at different juice boxes and find their unit rate by dividing the total ounces by the price to see which gives you the most juice for each dollar you spend!' },
        { title: 'Percent', summary: 'Percent means parts out of 100, and its everywhere around us! When you see 25%, that means 25 out of every 100 parts. Think about your phone battery at 75% - that means 75 out of 100 parts are charged up. If your class has 20 students and 5 wear glasses, thats 5 out of 20, which equals 25%. Try this fun activity: look around your classroom and count different things like students wearing sneakers versus other shoes, then figure out what percent each group represents. You can also practice with your test scores - if you got 18 out of 20 questions right, thats 90%! Understanding percent helps' },
      ], questions: [
        { id: '6-M-Q1-1', q: 'What is 50% as a decimal?', type: 'mc', options: ['0.5', '0.05', '5.0'], answer: 0 },
        { id: '6-M-Q1-2', q: 'Ratio 2:3 means for every 2 of A there are ___ of B.', type: 'mc', options: ['2', '3', '5'], answer: 1 },
      ]},
      { name: 'Q2 — Fractions/Decimals/Percent', lessons: [
        { title: 'Convert All Three', summary: 'Converting between fractions, decimals, and percentages is like learning to speak three different math languages that all say the same thing! Think of 1/2, 0.5, and 50% as three ways to describe half of something. To convert a fraction to a decimal, divide the top number by the bottom number, like 3/4 becomes 0.75. To make a decimal into a percentage, multiply by 100, so 0.75 becomes 75%. To change a percentage back to a fraction, put it over 100 and simplify, so 75% becomes 75/100 which reduces to 3/4. Try this fun activity: pick your favorite pizza topping and imagine ordering different amou' },
        { title: 'Percent Problems', summary: 'Understanding percent problems is like being a detective with numbers! A percent means out of 100, so when you see 25%, think of it as 25 out of every 100 items. Lets say your class of 20 students wants to find what 25% looks like - that would be 5 students since 25% of 20 equals 5. To solve percent problems, you can use the strategy of finding 10% first by moving the decimal point one place left, then building up to your answer. Try this fun challenge: if 40% of your Halloween candy is chocolate and you have 30 pieces total, how many chocolate pieces do you have? Start by finding 10% of 30 w' },
        { title: 'Real Life', summary: 'Fractions, decimals, and percentages are everywhere in your daily life and understanding them helps you make smart decisions! When youre shopping with your family, you might see that a video game is 25% off, which means you save 1/4 of the original price, or 0.25 as a decimal. If your favorite pizza place gives you 3/4 of a large pizza and your friend gets 0.75 of the same size, you both got exactly the same amount since 3/4 equals 0.75 and also equals 75%. Try this fun activity: look around your home and find three examples of fractions, decimals, or percentages, like measuring cups showing ' },
      ], questions: [
        { id: '6-M-Q2-1', q: '20% of 80 = ?', type: 'mc', options: ['16', '20', '8'], answer: 0 },
        { id: '6-M-Q2-2', q: '1/4 = ___%', type: 'mc', options: ['20', '25', '30'], answer: 1 },
      ]},
      { name: 'Q3 — Integers', lessons: [
        { title: 'Negative Numbers', summary: 'Negative numbers are numbers that are less than zero, and we use a minus sign in front of them to show theyre below zero on the number line. Think of negative numbers like going down floors in a building or temperatures below freezing - if its 5 degrees below zero, we write it as -5. You can see negative numbers everywhere, from elevator buttons that show basement levels like -1 and -2, to winter temperatures, to owing money or points in games. Lets practice by drawing a number line from -10 to 10 and taking turns calling out temperatures or elevator floors while pointing to where they belo' },
        { title: 'Add/Sub Integers', summary: 'Adding and subtracting integers is like playing a fun number game where you move forward and backward on a number line! When you add a positive integer, you move to the right, and when you subtract or add a negative integer, you move to the left. For example, if you start at 3 and add 5, you jump right to 8, but if you start at 3 and subtract 7, you move left and land at negative 4. Try this activity with a friend: draw a number line from negative 10 to positive 10, place a game piece at zero, then take turns rolling dice and moving right for even numbers and left for odd numbers to see where ' },
        { title: 'Coordinate Plane', summary: 'Imagine the coordinate plane as a treasure map with two number lines that cross like a big plus sign! The horizontal line is called the x-axis and the vertical line is the y-axis, and they meet at a special point called the origin where both equal zero. Every location on this map can be found using two numbers called coordinates, written as (x,y). For example, the point (3,2) means you move 3 steps right from the origin and 2 steps up. Try this fun activity: draw your own coordinate plane on graph paper and plot your favorite animals at different points, like putting a lion at (4,1) and an ele' },
      ], questions: [
        { id: '6-M-Q3-1', q: '-4 + 9 = ?', type: 'mc', options: ['5', '-5', '13'], answer: 0 },
        { id: '6-M-Q3-2', q: 'The coordinate plane has ___ quadrants.', type: 'mc', options: ['4', '2', '6'], answer: 0 },
      ]},
      { name: 'Q4 — Expressions', lessons: [
        { title: 'Variables', summary: 'Variables are like mystery boxes in math that hold unknown numbers we need to figure out! Just like how you might use a letter to represent your friends name in a story, mathematicians use letters like x, y, or n to represent unknown numbers in expressions and equations. For example, if you have 5 + x = 12, the variable x is hiding the number 7 because 5 + 7 equals 12. Try this fun activity: create your own variable expressions using your age as the mystery number, like a + 3 where a represents your age, then have classmates guess what a could be by solving the expression!' },
        { title: 'Order of Operations', summary: 'Order of operations is like following a recipe - you need to do things in the right order to get the correct answer! When solving math expressions, we follow PEMDAS: Parentheses first, then Exponents, then Multiplication and Division from left to right, and finally Addition and Subtraction from left to right. Lets try 3 + 2 × 4. We multiply first: 2 × 4 = 8, then add: 3 + 8 = 11. Now practice with expressions like 15 - 3 × 2 + 1 and see if you can solve them step by step using our special order!' },
        { title: 'Simple Equations', summary: 'Simple equations are like math puzzles where we need to find the missing number, and we use a letter like x to represent that mystery number! Think of it as a balance scale where both sides must be equal. For example, if we have x + 3 = 7, we ask ourselves what number plus 3 equals 7, and we discover that x = 4 because 4 + 3 = 7. To practice, try solving n + 5 = 12 by thinking about what number added to 5 gives us 12, then check your answer by substituting it back into the original equation to make sure both sides balance perfectly.' },
      ], questions: [
        { id: '6-M-Q4-1', q: '3 + 4 × 2 = ? (order of operations)', type: 'mc', options: ['11', '14', '20'], answer: 0 },
        { id: '6-M-Q4-2', q: 'If x + 5 = 12, then x = ___', type: 'mc', options: ['6', '7', '8'], answer: 1 },
      ]},
    ]},
    { name: 'Language Arts', units: [
      { name: 'Q1 — Reading', lessons: [
        { title: 'Theme & Symbol', summary: 'When you read stories, authors hide special meanings called themes and use symbols to make their stories deeper and more interesting. A theme is the big message or lesson the author wants you to learn, like friendship is important or being brave helps you overcome challenges. Symbols are objects or things that represent something bigger than themselves, just like how a dove often represents peace or a red rose might represent love. For example, in many fairy tales, a mirror might symbolize truth or vanity, while the theme could be that inner beauty matters more than outer beauty. To practice f' },
        { title: 'Text Evidence', summary: 'When you read stories or articles, you become a detective looking for clues that support your ideas about the text. Text evidence is like finding puzzle pieces that prove what you think is true about characters, events, or the authors message. For example, if you believe a character is brave, you would look for specific actions or words in the story that show their courage, like when they help someone in danger or face their fears. To practice finding text evidence, try the evidence hunt game where you write down one thing you notice about the main character, then search through the text to f' },
        { title: 'Compare Authors', summary: 'When you read books by different authors, you become a reading detective looking for clues about their unique writing styles! Just like how your friends each have their own way of telling stories, authors have special techniques that make their writing special. For example, one author might love using lots of descriptive words that paint vivid pictures in your mind, while another author might focus on fast-paced action and exciting dialogue between characters. Try this fun activity: pick two books from different authors and create a comparison chart listing how each author makes you feel when ' },
      ], questions: [
        { id: '6-L-Q1-1', q: 'A symbol stands for ___', type: 'mc', options: ['an idea', 'a color', 'a number'], answer: 0 },
        { id: '6-L-Q1-2', q: 'Good answers use ___ from the text.', type: 'mc', options: ['evidence', 'guesses', 'opinion only'], answer: 0 },
      ]},
      { name: 'Q2 — Grammar', lessons: [
        { title: 'Parts of Speech Review', summary: 'Welcome back to our exciting journey through the building blocks of language called parts of speech! Just like a house needs different materials like bricks, wood, and nails, sentences need different types of words to make them strong and clear. The eight main parts of speech are nouns that name people, places, and things like teacher or playground, verbs that show action or being like run or is, adjectives that describe nouns like big or colorful, adverbs that tell us more about verbs like quickly or carefully, pronouns that replace nouns like she or they, prepositions that show relationships' },
        { title: 'Active/Passive', summary: 'Lets explore active and passive voice, which is all about who or what is doing the action in a sentence! In active voice, the subject does the action, like The dog chased the ball where the dog is actively chasing. In passive voice, the subject receives the action, like The ball was chased by the dog where the ball is having something done to it. Active voice usually sounds more direct and exciting, while passive voice can make writing feel distant or formal. Try this fun activity: write five sentences about your favorite sport using active voice, then rewrite them in passive voice and notice' },
        { title: 'Sentence Types', summary: 'Learning about sentence types is like discovering different flavors of ice cream - each one serves a special purpose! There are four main types: declarative sentences make statements like My dog loves to play fetch, interrogative sentences ask questions like What time is dinner, imperative sentences give commands like Please clean your room, and exclamatory sentences show strong feelings like That movie was amazing! To practice, try writing one example of each type about your favorite hobby, then read them aloud to hear how different they sound when you change the punctuation and tone.' },
      ], questions: [
        { id: '6-L-Q2-1', q: '"Close the door!" is ___', type: 'mc', options: ['imperative', 'question', 'statement'], answer: 0 },
        { id: '6-L-Q2-2', q: 'In "The ball was thrown by Sam", the voice is ___', type: 'mc', options: ['passive', 'active', 'none'], answer: 0 },
      ]},
      { name: 'Q3 — Writing', lessons: [
        { title: 'Essay Structure', summary: 'Think of your essay like building a house - you need a strong foundation and clear rooms! Every good essay has three main parts: an introduction that welcomes readers and tells them what youll write about, body paragraphs that give your main ideas with details and examples, and a conclusion that wraps everything up nicely. For example, if youre writing about your favorite animal, start by introducing the animal and why its special, then write separate paragraphs about its appearance, habitat, and interesting behaviors, and finish by reminding readers why this animal is so amazing. Now try o' },
        { title: 'Revise & Edit', summary: 'When you finish writing your first draft, its time to revise and edit to make your work shine! Revising means looking at the big picture like adding details, moving sentences around, or changing words to make your ideas clearer. Editing focuses on fixing smaller mistakes like spelling, punctuation, and grammar. Think of revising as redecorating a room and editing as cleaning it up! For example, if you wrote The dog ran fast, you might revise it to The golden retriever sprinted across the muddy field, then edit to make sure you spelled retriever correctly. Try this fun activity: read your writ' },
        { title: 'Research', summary: 'Research is like being a detective who gathers clues to solve a mystery or learn something new! When you research, you collect information from different sources like books, websites, or interviews to answer questions or support your ideas in writing. For example, if youre writing about dolphins, you might read encyclopedia articles, watch nature videos, and visit an aquarium website to learn about their habitat, diet, and behaviors. Good researchers always check multiple sources to make sure their information is accurate and reliable. Try this detective activity: pick an animal youre curiou' },
      ], questions: [
        { id: '6-L-Q3-1', q: 'A thesis is the essay’s ___', type: 'mc', options: ['main claim', 'title', 'conclusion'], answer: 0 },
        { id: '6-L-Q3-2', q: 'Which is a good thesis for an essay on why reading matters?', type: 'mc', options: ['Reading develops critical thinking skills essential for success.', 'Books have pages.', 'Some people read books.'], answer: 0 },
      ]},
      { name: 'Q4 — Speaking', lessons: [
        { title: 'Oral Report', summary: 'In this quarter, youll become an expert presenter by creating and delivering your very own oral report! An oral report is when you research a topic youre curious about and share what you learned with your classmates using your voice, body language, and maybe some visual aids like posters or props. Think about how a nature documentary host explains fascinating animal behaviors or how a museum guide shares cool facts about dinosaurs. For your oral report, you might choose to explore topics like your favorite animal, a country youd love to visit, an inspiring person from history, or even how y' },
        { title: 'Debate', summary: 'Debate is when people share different opinions about a topic and try to convince others using facts and good reasons. Think about when your class discusses whether students should have longer recess - some might argue it helps kids stay healthy and focused, while others say it takes away from learning time. Both sides listen respectfully and explain their thinking with examples. Today well practice debating whether pets should be allowed in school by splitting into two teams, preparing our best arguments with supporting details, then taking turns presenting our cases while the other team list' },
        { title: 'Listening', summary: 'Listening is one of the most important skills for great speaking because it helps you understand what others are saying and respond thoughtfully. Good listeners pay attention with their eyes, ears, and hearts, showing they care about the speakers message. For example, when your friend tells you about their weekend, a good listener looks at them, nods to show understanding, and asks follow-up questions like "What was your favorite part?" Try this fun listening activity with a partner: one person describes their dream vacation for two minutes while the other listens carefully without interrupti' },
      ], questions: [
        { id: '6-L-Q4-1', q: 'In a debate you ___ your view.', type: 'mc', options: ['defend', 'hide', 'drop'], answer: 0 },
        { id: '6-L-Q4-2', q: 'Good listening means ___', type: 'mc', options: ['paying attention', 'talking over', 'leaving'], answer: 0 },
      ]},
    ]},
    { name: 'Spelling & Word Origins', units: [
      { name: 'Q1 — Latin Roots 4', lessons: [
        { title: 'List 1: duct, form', summary: 'Today well explore two powerful Latin roots that appear in many English words! The root duct means to lead or guide, like in the word conduct where someone leads a group or orchestra. The root form means to shape or make, which you can see in words like transform when something changes its shape completely. Lets play a word detective game where you find these roots hiding in everyday words like aqueduct, format, and uniform, then create sentences showing how each word uses the meaning of leading or shaping.' },
        { title: 'Root: duct = "lead"', summary: 'The Latin root duct means lead, and you can find it hiding in many English words you already know! When you conduct an orchestra, you lead the musicians through the music. A conductor on a train leads passengers safely to their destination. Even when you deduce something, you lead your mind through clues to find an answer. Try this fun challenge: look around your classroom and house this week to spot other duct words likeduct tape, aqueduct, or product, then think about how each one connects to the idea of leading or guiding something along a path.' },
        { title: 'Root: form = "shape"', summary: 'The Latin root form means shape, and you can find it in many English words! When you transform something, you change its shape or form into something new, like when a caterpillar transforms into a butterfly. The word uniform describes things that have the same shape or appearance, like school uniforms that make everyone look similar. Try this fun activity: look around your classroom and find three objects, then think of how you could transform each one into something completely different by changing its shape or purpose!' },
      ], questions: [
        { id: '6-SP-Q1-1', q: '"conduct" means to ___', type: 'mc', options: ['lead', 'shape', 'say'], answer: 0 },
        { id: '6-SP-Q1-2', q: '"reform" means to ___ again.', type: 'mc', options: ['shape/improve', 'lead', 'write'], answer: 0 },
      ]},
      { name: 'Q2 — Greek Roots 4', lessons: [
        { title: 'List 2: meter, scope', summary: 'Lets explore two more Greek roots that help us understand measurement and observation! The root meter means measure, like in thermometer which measures temperature, and perimeter which measures the distance around something. The root scope means to look or see, like in telescope which helps us see far away objects, and microscope which lets us look at tiny things up close. Try this fun activity: walk around your classroom or home and find three objects that relate to measuring or looking, then create new words by combining meter or scope with other word parts you know, like watermeter for mea' },
        { title: 'Root: meter = "measure"', summary: 'The Greek root meter means measure, and you can find it in lots of words you already know! A thermometer measures temperature, a speedometer in a car measures how fast youre going, and the perimeter of a shape measures the distance around its edges. Even geometry is about measuring earth and spaces! Try this fun challenge: look around your classroom or home and see how many things you can spot that measure something, then check if their names contain the root meter. You might discover a barometer that measures air pressure or notice that a centimeter measures tiny distances. Understanding thi' },
        { title: 'Root: scope = "see/observe"', summary: 'The Greek root scope means to see or observe, and you can find it in many English words that have to do with looking at things. A telescope helps you see far away objects like stars and planets, while a microscope lets you observe tiny things like cells and bacteria up close. A periscope is used in submarines to see above the water surface. Even when you go to the movies, you might hear someone say they want to scope out the best seats, which means to look around and find them. Try this fun activity: walk around your classroom or home and make a list of everything you can observe with your eye' },
      ], questions: [
        { id: '6-SP-Q2-1', q: 'A "thermometer" measures ___', type: 'mc', options: ['heat', 'light', 'sound'], answer: 0 },
        { id: '6-SP-Q2-2', q: 'A "telescope" lets you ___ far away.', type: 'mc', options: ['see', 'measure', 'hear'], answer: 0 },
      ]},
      { name: 'Q3 — Prefixes 2', lessons: [
        { title: 'List 3: sub-, inter-, trans-', summary: 'Ready to explore three more amazing prefixes that will boost your vocabulary power? Lets dive into sub-, inter-, and trans-! The prefix sub- means under or below, like in submarine (a boat that goes under water) or subway (an underground train). The prefix inter- means between or among, such as in international (between nations) or interact (to act between people). The prefix trans- means across or through, like in transportation (moving across distances) or translate (changing words across languages). Try this fun activity: write down five words you know that start with each prefix, then use' },
        { title: 'Prefix: sub- = "under"', summary: 'Lets explore the prefix sub- which means under! When you add sub- to the beginning of a word, it creates a new meaning related to being beneath or below something. For example, a submarine travels under the water, and the subway runs under the ground. Think about other sub- words you know like subtitle, which appears under the main title, or subzero temperatures that fall below zero degrees. Try this fun activity: look around your classroom or home and see if you can spot things that are sub- or under other things, then create new sub- words to describe what you see!' },
        { title: 'Prefix: inter- = "between"', summary: 'The prefix inter- means between and helps us understand words that describe things happening between two or more places or people. When you see inter- at the start of a word, think about connection or something in the middle. For example, an interstate highway goes between different states, and international means between nations or countries. Try this fun activity: look around your classroom and find things that connect or go between other things, then see if you can create new inter- words to describe them, like interdoor for the space between doors or interdesk for the area between student ' },
      ], questions: [
        { id: '6-SP-Q3-1', q: '"subway" runs ___ the ground.', type: 'mc', options: ['under', 'over', 'around'], answer: 0 },
        { id: '6-SP-Q3-2', q: '"interact" means to act ___ people.', type: 'mc', options: ['between/with', 'against', 'without'], answer: 0 },
      ]},
      { name: 'Q4 — Review', lessons: [
        { title: 'Master List', summary: 'Welcome back, amazing learners! A master list is like being the ultimate organizer - its one big, complete list that contains all the important items from smaller lists combined together. Think of it like collecting all your favorite songs from different playlists and putting them into one super playlist that has everything you love! When you make a master list of your school supplies by combining your math supplies, art supplies, and reading supplies into one complete list, you can see everything you need at once. Lets practice by creating a master list of our classs favorite books - each ' },
        { title: 'Root Map', summary: 'Lets explore how roots work like a map to help us understand word meanings! Just like a treasure map shows you where to find gold, word roots show you the core meaning hidden inside words. Take the root "port" which means "to carry" - you can find it in words like transport (carry across), export (carry out), and portable (able to be carried). Now grab your detective hat and become a root explorer! Pick three words from your reading book that look similar and see if you can discover their shared root. Write down what you think the root means, then check if that meaning makes sense in all thre' },
        { title: 'Decode Challenge', summary: 'Get ready for an exciting Decode Challenge where youll become a secret agent cracking codes! Decoding means figuring out hidden messages by looking for patterns and clues. For example, if A=1, B=2, C=3, then the code 8-5-12-16 spells HELP! Your mission is to solve three mystery codes using different methods like number substitution, backwards writing, and skip patterns. Work with a partner to decode faster and remember that good detectives always look for repeating letters or common words like THE or AND to help crack the puzzle. Once you solve all three codes, theyll reveal the location of ' },
      ], questions: [
        { id: '6-SP-Q4-1', q: 'Which word contains the root "meter" (meaning measure)?', type: 'mc', options: ['thermometer', 'metal', 'meeting'], answer: 0 },
        { id: '6-SP-Q4-2', q: 'A prefix goes ___ the root.', type: 'mc', options: ['before', 'after', 'inside'], answer: 0 },
      ]},
    ]},
    { name: 'Science', units: [
      { name: 'Q1 — Cell Biology', lessons: [
        { title: 'Cell Parts', summary: 'Cells are like tiny factories with special parts that each have important jobs to keep living things healthy and working properly. Just like your body has a heart to pump blood and lungs to help you breathe, cells have parts called organelles that do specific tasks. The nucleus acts like the brain of the cell and controls everything that happens, while the cell membrane works like a protective wall that decides what can come in and go out. You can think of mitochondria as the power stations that give the cell energy to do its work, and chloroplasts in plant cells are like tiny solar panels tha' },
        { title: 'Photosynthesis', summary: 'Photosynthesis is like natures amazing cooking recipe that plants use to make their own food! Just like you need ingredients to bake cookies, plants need sunlight, water, and carbon dioxide from the air to create sugar for energy. The green parts of leaves contain special helpers called chloroplasts that capture sunlight and mix everything together. Think about a big oak tree in your yard - its constantly using this process to grow taller and stronger while also giving us fresh oxygen to breathe. You can see photosynthesis in action by placing a clear plastic bag over some leaves on a sunny ' },
        { title: 'Classification', summary: 'Classification in cell biology is like organizing your room - scientists group living things based on what they have in common to better understand them! For example, all animals have cells without cell walls, while plants have cells with thick cell walls and can make their own food through photosynthesis. Try this fun activity: look around your classroom and group objects by their similarities, just like scientists classify cells and organisms based on their special features and functions.' },
      ], questions: [
        { id: '6-SC-Q1-1', q: 'Photosynthesis happens in ___', type: 'mc', options: ['leaves', 'roots', 'stems'], answer: 0 },
        { id: '6-SC-Q1-2', q: 'The "powerhouse" of the cell is the ___', type: 'mc', options: ['mitochondria', 'nucleus', 'wall'], answer: 0 },
      ]},
      { name: 'Q2 — Earth', lessons: [
        { title: 'Rock Cycle', summary: 'The amazing rock cycle shows us how rocks are constantly changing from one type to another over millions of years, just like natures own recycling system! When sedimentary rocks like sandstone get squeezed and heated deep underground, they transform into metamorphic rocks such as quartzite, and when any rock melts completely and cools down, it becomes igneous rock like granite. You can model this incredible process at home by pressing playdough layers together to make sedimentary rock, then squishing and warming it in your hands to create metamorphic rock, and finally melting crayons to see h' },
        { title: 'Fossils', summary: 'Fossils are the preserved remains or traces of ancient plants and animals that lived millions of years ago, like natures own time capsules that help us learn about Earths incredible history. When a dinosaur died long ago, sometimes its bones got buried under layers of sand and mud, and over millions of years, minerals slowly replaced the bone material, turning it into stone while keeping the same shape. You can become a fossil detective by examining different types of fossils to discover what creatures looked like, what they ate, and how they lived, or even create your own fossil models usin' },
        { title: 'Natural Resources', summary: 'Natural resources are amazing gifts from Earth that we use every day to live and create the things we need. These special materials come from nature and include water we drink, air we breathe, trees that become paper and furniture, rocks and metals for building, and soil where our food grows. Some resources like sunlight and wind are renewable because they never run out, while others like oil and coal take millions of years to form and can be used up. You can become a natural resource detective by walking around your home and identifying what things came from Earth, like the wood in your desk,' },
      ], questions: [
        { id: '6-SC-Q2-1', q: 'Fossils are ___ of past life.', type: 'mc', options: ['records', 'pictures', 'toys'], answer: 0 },
        { id: '6-SC-Q2-2', q: 'Solar power is ___', type: 'mc', options: ['renewable', 'nonrenewable', 'finite'], answer: 0 },
      ]},
      { name: 'Q3 — Space', lessons: [
        { title: 'Solar System', summary: 'Our amazing solar system is like a cosmic neighborhood with the Sun as the bright center and eight planets orbiting around it like a giant merry-go-round. Earth is the third planet from the Sun, sitting in just the right spot where its not too hot like Mercury or too cold like Neptune. To help remember the order of planets, try this fun memory trick: My Very Educated Mother Just Served Us Nachos, which stands for Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, and Neptune. Create your own solar system model using different sized balls or even fruits to show how the planets compare in si' },
        { title: 'Stars & Galaxies', summary: 'When you look up at the night sky, those twinkling points of light are actually giant balls of hot gas called stars, just like our Sun but much farther away! Stars come together in huge groups called galaxies, and our galaxy is called the Milky Way, which contains over 100 billion stars. For example, the North Star has helped sailors navigate for thousands of years because it stays in the same spot in the sky. Try this fun activity: on a clear night, go outside with an adult and see how many stars you can count in a small section of sky, then imagine that there are billions more just like them' },
        { title: 'Space Exploration', summary: 'Space exploration is humanitys incredible journey to discover what lies beyond our planet Earth. Scientists and astronauts use powerful rockets and spacecraft to travel to places like the Moon, Mars, and even beyond our solar system. For example, NASAs rovers have been driving around on Mars taking photos and collecting rock samples to help us learn about the red planet. You can become a space explorer too by observing the night sky with binoculars, tracking the International Space Station as it passes overhead, or building your own model rocket to understand how spacecraft blast off into th' },
      ], questions: [
        { id: '6-SC-Q3-1', q: 'Our galaxy is the ___', type: 'mc', options: ['Milky Way', 'Andromeda', 'Pinwheel'], answer: 0 },
        { id: '6-SC-Q3-2', q: 'A rover explores ___', type: 'mc', options: ['planets', 'oceans', 'clouds'], answer: 0 },
      ]},
      { name: 'Q4 — Engineering', lessons: [
        { title: 'Design Process', summary: 'Engineering is like being a detective and inventor rolled into one! The design process is the special set of steps engineers follow to solve problems and create amazing things. First, they ask questions to understand the problem, then imagine different solutions, plan their best idea, create a prototype or model, test it to see if it works, and improve it based on what they learn. For example, when engineers wanted to help people cross a busy river, they asked what was needed, imagined bridges, boats, and tunnels, chose the best option, built a small model bridge, tested how much weight it cou' },
        { title: 'Bridges', summary: 'Have you ever wondered how bridges stay up when heavy trucks drive across them? Bridges are amazing engineering structures that help us cross rivers, valleys, and busy roads safely. Engineers design different types of bridges depending on what they need to cross and how much weight they need to carry. The Golden Gate Bridge in San Francisco uses strong cables to suspend the roadway, while beam bridges like many highway overpasses use thick concrete or steel beams for support. Try building your own bridge using books as supports and a ruler as the span, then test how many coins it can hold befo' },
        { title: 'Green Tech', summary: 'Green technology is engineering that helps protect our planet by using less energy and creating less pollution. Engineers design amazing inventions like solar panels that turn sunlight into electricity for our homes, wind turbines that spin in the breeze to power entire towns, and electric cars that run quietly without harmful exhaust fumes. These clever solutions help keep our air and water clean while still giving us the energy we need for daily life. You can be a green engineer too by designing your own mini solar oven using a pizza box, aluminum foil, and plastic wrap to cook smores using' },
      ], questions: [
        { id: '6-SC-Q4-1', q: 'The design process ends with ___', type: 'mc', options: ['testing', 'guessing', 'stopping'], answer: 0 },
        { id: '6-SC-Q4-2', q: 'Engineers solve problems by ___', type: 'mc', options: ['building and testing', 'wishing', 'waiting'], answer: 0 },
      ]},
    ]},
    { name: 'History & Geography', units: [
      { name: 'Q1 — Ancient Civilizations', lessons: [
        { title: 'Mesopotamia', summary: 'Mesopotamia, known as the cradle of civilization, was located between the Tigris and Euphrates rivers in what is now Iraq around 5,000 years ago. This ancient land was home to the worlds first cities, where people invented writing called cuneiform by pressing wedge-shaped marks into clay tablets to keep records and tell stories. The Mesopotamians also created the first laws, built amazing ziggurats that reached toward the sky, and developed the wheel that revolutionized transportation. Try creating your own cuneiform message by pressing a pencil tip into soft clay to form wedge shapes, then c' },
        { title: 'Egypt', summary: 'Ancient Egypt was one of the worlds most amazing civilizations that lasted for over 3,000 years along the life-giving Nile River. The Egyptians built incredible pyramids as tombs for their pharaohs, with the Great Pyramid of Giza being one of the Seven Wonders of the Ancient World. They also created hieroglyphics, a fascinating writing system using pictures and symbols to represent words and sounds. Egyptian society was highly organized, with pharaohs at the top, followed by nobles, priests, scribes, craftsmen, and farmers. They believed strongly in the afterlife and mummified bodies to prese' },
        { title: 'Greece', summary: 'Ancient Greece was one of the most amazing civilizations in history, made up of hundreds of independent city-states that shared the same language and culture but ruled themselves differently. The most famous city-state was Athens, where people invented democracy and citizens could vote on important decisions, while Sparta was known for training the strongest warriors in the ancient world. Greek people gave us incredible gifts that we still use today, including the Olympic Games, fascinating myths about gods like Zeus and Athena, beautiful architecture with tall columns, and even our alphabet. ' },
      ], questions: [
        { id: '6-H-Q1-1', q: 'Democracy began in ___', type: 'mc', options: ['Greece', 'Egypt', 'Rome'], answer: 0 },
        { id: '6-H-Q1-2', q: 'The Nile River is in ___', type: 'mc', options: ['Egypt', 'Greece', 'China'], answer: 0 },
      ]},
      { name: 'Q2 — Rome', lessons: [
        { title: 'Republic', summary: 'The Roman Republic was like a giant classroom where citizens got to vote on important decisions instead of having just one king make all the rules. Starting around 509 BCE, Romans elected leaders called senators and consuls who worked together to govern their growing territory. For example, when Rome needed to decide whether to build new roads or go to war with neighboring cities, citizens would gather in the Forum to debate and vote. Try this activity: create your own classroom republic by electing student representatives to make decisions about fun activities, class rules, or how to organize' },
        { title: 'Empire', summary: 'The Roman Empire was like a giant puzzle that grew piece by piece as Roman armies conquered new lands and people across Europe, Africa, and Asia. At its biggest around 117 AD, the empire stretched from Britain in the north all the way to Egypt in the south, and from Spain in the west to modern-day Iraq in the east, making it one of the largest empires in history. To explore how big this empire really was, grab a world map and use different colored pencils to trace the borders of Roman territory, then calculate how many modern countries would fit inside this ancient superpower.' },
        { title: 'Fall & Legacy', summary: 'The mighty Roman Empire that once ruled most of the known world eventually became too big and difficult to manage, leading to its gradual fall around 476 CE when barbarian tribes took over the western territories. Even though Rome fell, its incredible legacy lives on today in amazing ways that touch our daily lives. For example, many English words come from Latin like "family" and "school," our legal systems use Roman ideas about justice and laws, and Roman architectural innovations like concrete, arches, and domes can be seen in buildings from the U.S. Capitol to your local courthouse. To exp' },
      ], questions: [
        { id: '6-H-Q2-1', q: 'Rome began as a ___', type: 'mc', options: ['republic', 'empire', 'kingdom'], answer: 0 },
        { id: '6-H-Q2-2', q: 'Roman ___ spread across the empire.', type: 'mc', options: ['roads', 'rivers', 'mountains'], answer: 0 },
      ]},
      { name: 'Q3 — World Geography', lessons: [
        { title: 'Continents & Oceans', summary: 'Our amazing planet Earth is divided into seven continents and five oceans that work together like pieces of a giant puzzle! The continents are large landmasses where we live, including North America where countries like the United States and Canada are located, Asia which is home to China and India, and Africa where you can find Egypt and Kenya. The five oceans are massive bodies of saltwater that connect all the continents, with the Pacific Ocean being the largest and the Arctic Ocean being the smallest and coldest. Try this fun activity with a friend: take turns naming a continent, then chal' },
        { title: 'Climate Zones', summary: 'Climate zones are large areas of Earth that have similar weather patterns throughout the year, and scientists have identified five main types that help us understand our planet better. The tropical zone near the equator stays hot and humid year-round with places like the Amazon rainforest, while the polar zones at the North and South poles remain freezing cold with ice and snow like Antarctica. Between these extremes, we find temperate zones with four distinct seasons like most of the United States, dry desert zones with very little rainfall like the Sahara, and highland zones in mountainous a' },
        { title: 'Culture Regions', summary: 'Culture regions are special areas around the world where people share similar ways of living, like the same language, food, music, and traditions. Think about how people in Mexico might speak Spanish, eat tacos, and celebrate Dia de los Muertos, while people in Japan speak Japanese, enjoy sushi, and honor their ancestors during Obon festival. These shared customs help create invisible boundaries that geographers call culture regions. You can explore this concept by researching a culture region that interests you and creating a colorful poster showing their language, traditional foods, clothing' },
      ], questions: [
        { id: '6-H-Q3-1', q: 'The largest ocean is the ___', type: 'mc', options: ['Pacific', 'Atlantic', 'Indian'], answer: 0 },
        { id: '6-H-Q3-2', q: 'Tropical climates are ___', type: 'mc', options: ['warm', 'cold', 'icy'], answer: 0 },
      ]},
      { name: 'Q4 — US Before 1800', lessons: [
        { title: 'Indigenous Nations', summary: 'Long before European explorers arrived in America, hundreds of Indigenous nations had been living here for thousands of years, each with their own unique cultures, languages, and ways of life. For example, the Haudenosaunee people in the Northeast lived in longhouses and formed a powerful alliance called the Six Nations, while the Pueblo peoples in the Southwest built amazing cliff dwellings and were skilled farmers who grew corn, beans, and squash together. These diverse nations had complex governments, trade networks that stretched across the continent, and deep spiritual connections to the ' },
        { title: 'Colonies', summary: 'Long before the United States became a country, European explorers sailed across the Atlantic Ocean and established colonies along the eastern coast of North America. A colony is like a town or area that belongs to and is controlled by another country far away. The thirteen original colonies, including Virginia, Massachusetts, and Pennsylvania, were ruled by Great Britain even though they were thousands of miles away from England. People came to these colonies for many reasons - some wanted religious freedom, others hoped to find gold or start new businesses, and some were brought against thei' },
        { title: 'A New Nation', summary: 'A New Nation means the exciting time when America became its own country after winning independence from Britain in 1783! The new United States had to figure out how to govern itself, create laws, and work together as one nation instead of separate colonies. For example, the founders wrote the Constitution in 1787 to establish rules for how the government would work, including having a president, Congress, and courts. George Washington became the first president and helped set important traditions that future leaders would follow. Try this activity: imagine you and your classmates started a ne' },
      ], questions: [
        { id: '6-H-Q4-1', q: 'Before Europeans, America was home to ___', type: 'mc', options: ['indigenous nations', 'no one', 'one tribe'], answer: 0 },
        { id: '6-H-Q4-2', q: 'The Constitution was written in ___', type: 'mc', options: ['1776', '1787', '1791'], answer: 1 },
      ]},
    ]},
    { name: 'Bible & Character', units: [
      { name: 'Q1 — Genesis', lessons: [
        { title: 'Creation', summary: 'Creation is Gods amazing gift to us, like the most incredible art project ever made! In Genesis, we learn how God carefully designed everything from the sparkling stars to the tiniest flowers, and saved the best for last by creating people in His own image. Just like an artist who steps back to admire their masterpiece, God looked at everything He made and called it very good. Think about your favorite place in nature - maybe a beach, forest, or your backyard - and notice all the incredible details God included, from the colors of a sunset to the pattern on a butterflys wings. This week, try' },
        { title: 'Fall', summary: 'The Fall teaches us that sin entered the world when Adam and Eve disobeyed God by eating the forbidden fruit, breaking their perfect relationship with Him and bringing consequences like death and separation from God. Just like when we break a rule at home and feel distant from our parents, Adam and Eve felt ashamed and hid from God after their disobedience. Think about a time you made a wrong choice and how it affected your relationships - write about what happened and how you felt, then discuss with a partner how God still loves us even when we make mistakes, just like loving parents never st' },
        { title: 'Promise', summary: 'In Genesis, we see how God is a promise-keeping God who always follows through on what He says. When God promised Abraham that he would become the father of many nations even though he was very old and had no children, it seemed impossible, but God kept His word and gave Abraham a son named Isaac. Just like when your parents promise to take you somewhere special and you can trust they will do it, we can trust Gods promises because He has never broken one. This week, think of one promise God has made to us today and draw a picture showing how you can trust Him to keep it, then share your drawi' },
      ], questions: [
        { id: '6-B-Q1-1', q: 'God made the world in ___ days.', type: 'mc', options: ['6', '7', '1'], answer: 0 },
        { id: '6-B-Q1-2', q: 'The promise was to ___ all nations.', type: 'mc', options: ['bless', 'rule', 'forget'], answer: 0 },
      ]},
      { name: 'Q2 — The Exile', lessons: [
        { title: 'Why Exile', summary: 'Why did God allow His people to be taken away from their promised land? The exile happened because the Israelites had broken their special relationship with God by worshipping false idols and not following His loving commands, just like when we face consequences for not listening to our parents rules that are meant to protect us. Sometimes God uses difficult times to help people remember how much they need Him and to turn their hearts back to Him. Think about a time when you made a wrong choice and faced consequences - how did it help you learn and grow closer to the people who love you?' },
        { title: 'Hope in Captivity', summary: 'Hope in Captivity means finding light even in the darkest times, just like the Jewish people did when they were taken far from their homeland to Babylon. Even though they felt sad and missed Jerusalem terribly, they didnt give up - instead they kept their faith alive by remembering Gods promises, teaching their children about their heritage, and believing they would return home someday. Think about a time when you felt homesick at camp or when visiting relatives, but you held onto the hope of seeing your family again - thats similar to how the exiles felt but kept trusting in Gods plan. Fo' },
        { title: 'Return', summary: 'After being away from their homeland for many years, the Jewish people were finally allowed to return home, which we call the Return from Exile. This was like a family moving back to their childhood neighborhood after living far away - everything felt familiar but also different after so much time had passed. The people had to rebuild their temple, replant their gardens, and reconnect with their traditions while also bringing new wisdom they had learned during their time away. Think about a time when you returned somewhere special after being gone for a while - maybe your grandparents house o' },
      ], questions: [
        { id: '6-B-Q2-1', q: 'Even in exile, God ___ His people.', type: 'mc', options: ['stayed with', 'forgot', 'left'], answer: 0 },
        { id: '6-B-Q2-2', q: 'The people were sent away because they ___', type: 'mc', options: ['turned from God', 'built a wall', 'won a war'], answer: 0 },
      ]},
      { name: 'Q3 — The Gospels', lessons: [
        { title: 'Four Books', summary: 'The Gospels are four special books in the New Testament that tell us about Jesus life and teachings. Think of them like four friends who each share their favorite memories about the same amazing person - Matthew, Mark, Luke, and John each wrote their own account of Jesus story, but they all focus on different details that were important to them. For example, Matthew loved to show how Jesus fulfilled old promises, while Luke enjoyed sharing stories about how Jesus cared for everyone, especially those who felt left out. To help remember this, try creating four different drawings of the same sc' },
        { title: 'Kingdom of God', summary: 'The Kingdom of God is like a wonderful place where God is the loving king and everyone follows his ways of kindness, forgiveness, and caring for others. Jesus taught that this kingdom isnt just a faraway place but something we can experience right now when we choose to love and help people around us. For example, when you share your lunch with someone who forgot theirs or forgive a friend who hurt your feelings, youre living like citizens of Gods kingdom. Try this fun activity with your class: create a "Kingdom of God" poster showing all the ways people can show Gods love in action, like h' },
        { title: 'The Cross', summary: 'The cross is the most important symbol in Christianity because it reminds us of Jesuss incredible love and sacrifice for all people. When Jesus died on the cross, he took the punishment for all the wrong things people have ever done, like a best friend who gets in trouble to protect you from being blamed. This amazing act of love opened the way for everyone to have a friendship with God that lasts forever. You can see crosses in churches, on jewelry, and in art all around the world as a reminder of this gift. Try drawing different types of crosses you might see in your community and think abo' },
      ], questions: [
        { id: '6-B-Q3-1', q: 'There are ___ Gospels.', type: 'mc', options: ['4', '3', '2'], answer: 0 },
        { id: '6-B-Q3-2', q: 'Jesus said the greatest is the ___', type: 'mc', options: ['servant', 'ruler', 'richest'], answer: 0 },
      ]},
      { name: 'Q4 — Character in Action', lessons: [
        { title: 'Integrity', summary: 'Integrity means doing the right thing even when no one is watching, and being honest about who you are and what you believe. Think about finding someones lost wallet with money inside - a person with integrity would try to return it instead of keeping it, even if they knew theyd never get caught. When you have integrity, your actions match your values, like standing up for a friend whos being teased even when its not the popular thing to do. This week, practice integrity by keeping promises you make, telling the truth even when it might get you in trouble, and doing your homework without b' },
        { title: 'Humility', summary: 'Humility means recognizing that we dont know everything and being willing to learn from others, even when we might feel embarrassed or think were really good at something. When Maya thought she was the best reader in class, she felt too proud to join the reading group with students who read different books, but when she tried a harder book and struggled, she realized she could learn so much more by working with others and asking for help. This week, practice humility by asking someone to teach you something new, whether its a skill, a game, or even help with homework you find challenging.' },
        { title: 'Courage', summary: 'Courage means being brave enough to do whats right, even when you feel scared or worried about what others might think. Its like when you stand up for a classmate whos being teased, speak up in class when you have a different opinion, or try something new that makes you nervous. A great example is Malala Yousafzai, who courageously fought for girls education even when it was dangerous. Courage doesnt mean youre never afraid - it means you act despite your fear because you know its important. This week, practice small acts of courage by raising your hand to answer a question, introducing' },
      ], questions: [
        { id: '6-B-Q4-1', q: 'Integrity means doing right ___', type: 'mc', options: ['even when alone', 'only when watched', 'never'], answer: 0 },
        { id: '6-B-Q4-2', q: 'Humility puts others ___', type: 'mc', options: ['first', 'last', 'out'], answer: 0 },
      ]},
    ]},
  ])

export const CURRICULUM_PART2c: GradeCurriculum[] = [G6]
