// Larose Christian Academy — ORIGINAL Curriculum, Grades 2-6 (part 2 of 3)
// Same structure as part 1: 6 subjects, 4 quarters, lessons + 2 questions each unit.
// Spelling & Word Origins = one class. Etymology from grade 3 up is explicit.

import type { GradeCurriculum } from './curriculum'

const g = (
  grade: string,
  gradeNum: number,
  age: string,
  tagline: string,
  subjects: any
): GradeCurriculum => ({ grade, gradeNum, age, tagline, subjects })

// ====================== 2ND GRADE ======================
export const G2: GradeCurriculum = g('2nd Grade', 2, '7-8', 'Independent reading, real arithmetic, God’s world.',
  [
    { name: 'Mathematics', units: [
      { name: 'Q1 — Add & Subtract to 100', lessons: [
        { title: 'Two-Digit Facts', summary: 'Learning two-digit facts helps us become faster at adding and subtracting bigger numbers! When we see 20 + 30, we can think of it as 2 tens plus 3 tens equals 5 tens, which is 50. Try this fun game with a partner: one person shows fingers for tens and the other shows fingers for ones, then work together to find the total number you made!' },
        { title: 'Word Problems', summary: 'Word problems help us use math in real life! When we read a story with numbers, we look for clue words like more, altogether, left, or take away to know if we add or subtract. If Emma has 15 stickers and gets 12 more, we add to find she has 27 stickers altogether. Try acting out word problems with toys or drawing pictures to help you solve them step by step!' },
        { title: 'Even & Odd', summary: 'Understanding even and odd numbers is like sorting your toys into two special groups! Even numbers can be split into pairs with no leftovers, like 2, 4, 6, 8, and 10. Odd numbers always have one left over when you try to make pairs, like 1, 3, 5, 7, and 9. Try this fun activity: grab some small objects like blocks or crayons and practice grouping them by twos to discover if your number is even or odd!' },
      ], questions: [
        { id: '2-M-Q1-1', q: '23 + 14 = ?', type: 'mc', options: ['37', '38', '36'], answer: 0 },
        { id: '2-M-Q1-2', q: 'Is 8 even or odd?', type: 'short', answer: 'even' },
      ]},
      { name: 'Q2 — Place Value & Money', lessons: [
        { title: 'Hundreds', summary: 'When we count to really big numbers like 100, 200, or 300, were counting by hundreds! Think of hundreds like big boxes that hold 10 groups of 10 things each. If you have 2 dollar bills, thats 2 hundreds or 200 pennies! Lets practice by counting colorful blocks in groups of 100 - stack 10 rows of 10 blocks each, then count your hundreds towers: 100, 200, 300 and see how tall they get!' },
        { title: 'Count Bills', summary: 'Learning to count bills is like being a money detective! Bills are paper money that come in different amounts like $1, $5, $10, and $20. Each bill has a special number that tells us how much its worth. When we count bills, we add up all the numbers to find the total amount. For example, if you have two $1 bills and one $5 bill, you count 1 + 1 + 5 = $7 total. Try this fun activity: gather some play money or draw your own bills, then practice counting different combinations to see how much money you have altogether!' },
        { title: 'Make Change', summary: 'Making change is like being a math detective! When someone buys something that costs less than the money they give you, you need to figure out how much money to give back. If a toy costs 3 dollars and someone pays with 5 dollars, you count up from 3 to 5 to find the change is 2 dollars. Try this fun activity with play money: set up a pretend store with items priced at different amounts, then practice buying things and calculating how much change you should receive. Start with simple prices like 1, 2, or 5 dollars to make counting easier, and remember to always count carefully to make sure ever' },
      ], questions: [
        { id: '2-M-Q2-1', q: 'Value of 5 in 352?', type: 'mc', options: ['5', '50', '500'], answer: 1 },
        { id: '2-M-Q2-2', q: 'How many quarters in $1?', type: 'short', answer: '4' },
      ]},
      { name: 'Q3 — Intro Multiplication', lessons: [
        { title: 'Equal Groups', summary: 'Lets learn about equal groups, which is the beginning of multiplication! Equal groups means having the same number of things in each group. Imagine you have 3 baskets and you put 2 apples in each basket - thats equal groups because every basket has exactly 2 apples. Try this fun activity: use your toys or crayons to make equal groups of 3. Put the same number of items in each group and count how many you have altogether. Youll discover that equal groups help us count faster and see patterns in numbers!' },
        { title: 'Times Tables 2,5,10', summary: 'Learning times tables is like discovering magical number patterns that make math super fun! The 2, 5, and 10 times tables are perfect starting points because they have easy-to-spot patterns. When we multiply by 2, were doubling numbers like counting by twos: 2, 4, 6, 8, 10. The 5 times table always ends in 0 or 5: 5, 10, 15, 20, 25. The 10 times table is the easiest because we just add a zero to any number: 10, 20, 30, 40, 50. Try clapping and counting by 2s, then stomping and counting by 5s, and finally jumping while counting by 10s to feel these number patterns in your body.' },
        { title: 'Arrays', summary: 'Arrays are a fun way to organize things in neat rows and columns, just like arranging toys or snacks on a table! When we make an array, we put objects in straight lines going across and up and down, which helps us count and see groups more easily. For example, if you arrange 6 cookies in 2 rows with 3 cookies in each row, youve made a 2 by 3 array that shows 2 groups of 3 equals 6 total cookies. Try this at home by using small objects like buttons, crackers, or toy cars to create your own arrays on a placemat or paper, then count how many you have in each row and altogether.' },
      ], questions: [
        { id: '2-M-Q3-1', q: '3 × 4 = ?', type: 'mc', options: ['7', '12', '9'], answer: 1 },
        { id: '2-M-Q3-2', q: '5 × 10 = ?', type: 'short', answer: '50' },
      ]},
      { name: 'Q4 — Measurement & Fractions', lessons: [
        { title: 'Inches & Centimeters', summary: 'Lets explore how we measure things using inches and centimeters! An inch is about as long as your thumb from the knuckle to the tip, while a centimeter is much smaller - about the width of your pinky nail. We can use rulers to measure objects like pencils, books, or even our hands. A pencil might be 7 inches long or about 18 centimeters long - both measurements tell us the same length but use different units. Try measuring your favorite toy with a ruler and see how many inches or centimeters long it is!' },
        { title: 'Tell Time (Half Hour)', summary: 'Learning to tell time to the half hour is like solving a fun puzzle with clock hands! When the long minute hand points straight down to the 6 and the short hour hand is halfway between two numbers, we say its half past that hour. If the hour hand is between 2 and 3 with the minute hand on 6, its half past 2 or 2:30. Try making different half-hour times with a toy clock and say them out loud to practice this exciting new skill!' },
        { title: 'Halves & Fourths', summary: 'Lets explore halves and fourths together! When we cut something into 2 equal pieces, each piece is called a half. When we cut something into 4 equal pieces, each piece is called a fourth or quarter. Imagine cutting a yummy pizza into 2 equal slices - each slice is one half of the pizza! If we cut that same pizza into 4 equal slices, each slice is one fourth. Try this fun activity: fold a piece of paper in half, then open it and count the 2 equal parts. Now fold it in half again and open it - youll see 4 equal parts called fourths!' },
      ], questions: [
        { id: '2-M-Q4-1', q: 'How many halves make a whole?', type: 'mc', options: ['2', '3', '4'], answer: 0 },
        { id: '2-M-Q4-2', q: 'A clock showing 3:30 is ___', type: 'mc', options: ['half past three', 'quarter to three', 'three o’clock'], answer: 0 },
      ]},
    ]},
    { name: 'Language Arts', units: [
      { name: 'Q1 — Reading Fluency', lessons: [
        { title: 'Chapter Books', summary: 'Chapter books are longer stories divided into smaller sections called chapters, just like how your day is divided into morning, afternoon, and evening. Books like Frog and Toad or Mercy Watson have several short chapters that you can read one at a time. Try reading one chapter each day with a grown-up, then talk about what happened before starting the next chapter tomorrow.' },
        { title: 'Main Idea & Details', summary: 'When we read stories, theres always one big important idea called the main idea, and smaller pieces of information called details that tell us more about it. Think of a story about a dog playing in the park - the main idea is that the dog is having fun, and the details might be that the dog is running, wagging its tail, and chasing a ball. Lets practice by reading a short story together and finding the big idea first, then looking for all the little details that help us understand more about whats happening in our story.' },
        { title: 'Sequencing', summary: 'Sequencing means putting things in the right order, just like when you get dressed in the morning - first you put on your underwear, then your shirt, then your pants! When we read stories, events happen in a special order too. In the story of The Three Little Pigs, first the pigs build their houses, then the wolf comes to visit, and finally the pigs stay safe in the brick house. Lets practice sequencing by acting out your morning routine step by step, or we can draw three pictures showing what happens at the beginning, middle, and end of your favorite bedtime story!' },
      ], questions: [
        { id: '2-L-Q1-1', q: 'The main idea is ___', type: 'mc', options: ['the most important point', 'the last word', 'a picture'], answer: 0 },
        { id: '2-L-Q1-2', q: 'What comes after "first"?', type: 'mc', options: ['last', 'next', 'never'], answer: 1 },
      ]},
      { name: 'Q2 — Grammar', lessons: [
        { title: 'Nouns & Pronouns', summary: 'Lets learn about nouns and pronouns together! A noun is a word that names a person, place, animal, or thing like mom, school, cat, or ball. A pronoun is a special word that takes the place of a noun like he, she, it, or they. When we say Sarah is happy we use the noun Sarah, but we can also say she is happy using the pronoun she instead. Try this fun game: look around your classroom and point to different objects while saying their noun names out loud, then practice replacing some nouns with pronouns in simple sentences about your family and friends.' },
        { title: 'Verbs (Past/Tense)', summary: 'Verbs are action words that tell us what someone or something is doing, and we can use them to talk about things that already happened in the past! When we add -ed to most verbs, they become past tense, like walk becomes walked or jump becomes jumped. Some special verbs change completely, like go becomes went or eat becomes ate. Lets practice by acting out actions first in present tense, then saying what we did using past tense - I am running, now I ran!' },
        { title: 'Adjectives', summary: 'Adjectives are special describing words that tell us more about people, animals, and things around us! They help us paint pictures with words by sharing details like how something looks, feels, or sounds. For example, instead of just saying dog, we can say big brown dog or fluffy white dog to help others imagine exactly what we see. You can find adjectives everywhere - try looking around your classroom right now and describe what you notice using colorful words like bright, soft, round, or tiny to make your sentences more exciting and fun!' },
      ], questions: [
        { id: '2-L-Q2-1', q: 'Which is a pronoun?', type: 'mc', options: ['she', 'run', 'red'], answer: 0 },
        { id: '2-L-Q2-2', q: 'Past of "walk" is ___', type: 'short', answer: 'walked' },
      ]},
      { name: 'Q3 — Writing', lessons: [
        { title: 'Paragraphs', summary: 'A paragraph is a group of sentences that all talk about the same thing, just like how all your toys about animals might go in one toy box together. When you write about your pet dog, all the sentences about your dog stay together in one paragraph. You might write about what your dog looks like, what games you play together, and what your dog likes to eat. Try writing three sentences about your favorite food and put them all together to make your very first paragraph.' },
        { title: 'Narrative', summary: 'Stories are everywhere around us, and you can be a storyteller too! A narrative is simply a story that tells about something that happened, with a beginning, middle, and end. Think about your morning - first you woke up, then you brushed your teeth, and finally you came to school. Thats a narrative! Stories have characters who are the people or animals in the story, and they happen in different places called settings. Lets practice by drawing three pictures that show what you did yesterday - one picture for the beginning of your day, one for the middle, and one for the end, then tell your st' },
        { title: 'Friendly Letter', summary: 'Writing a friendly letter is a wonderful way to share your thoughts and feelings with someone special like a friend, family member, or pen pal! A friendly letter has five important parts that make it complete and caring. First, you write the date at the top so your reader knows when you wrote it. Next comes the greeting where you say hello using words like Dear followed by the persons name. The body is the main part where you share your news, ask questions, or tell a story about something fun that happened to you. Then you write a closing like Love or Your friend to show how you feel about th' },
      ], questions: [
        { id: '2-L-Q3-1', q: 'A paragraph starts with a ___ sentence.', type: 'mc', options: ['topic', 'ending', 'question'], answer: 0 },
        { id: '2-L-Q3-2', q: 'Write a friendly letter greeting (e.g. Dear ___).', type: 'short', answer: 'open' },
      ]},
      { name: 'Q4 — Poetry & Drama', lessons: [
        { title: 'Rhyme & Rhythm', summary: 'Poetry is like music made with words, and just like your favorite songs, poems have special patterns called rhyme and rhythm that make them fun to say and remember. Rhyme happens when words sound the same at the end, like cat and hat or tree and bee, while rhythm is the beat you feel when you clap along to the words, just like clapping to a drumbeat. When we put rhyming words together with a steady rhythm, we create poems that bounce and dance off our tongues, making them exciting to share with friends and family. Lets practice by saying simple rhyming pairs together and clapping our hands to' },
        { title: 'Plays', summary: 'Plays are special stories that people act out on a stage for others to watch! The actors pretend to be different characters and say words out loud while moving around. You might see a play about three little pigs building houses or children going on a magical adventure. Plays are fun because you can see the story happening right in front of you! Lets pretend to be characters from your favorite story and act it out together in our classroom.' },
        { title: 'Book Report', summary: 'When we finish reading a wonderful book, we can share what we learned by making a book report! A book report tells others about our favorite parts of the story and what happened to the characters. If you read a poem about a dancing cat or a play about friendly monsters, you can draw pictures of your favorite scenes and tell your family what made you happy, sad, or excited. You can even act out the best parts or make up your own ending to share with your class during story time.' },
      ], questions: [
        { id: '2-L-Q4-1', q: 'A poem often has ___', type: 'mc', options: ['rhyme', 'only facts', 'no lines'], answer: 0 },
        { id: '2-L-Q4-2', q: 'Name the author of a book you read.', type: 'short', answer: 'open' },
      ]},
    ]},
    { name: 'Spelling & Word Origins', units: [
      { name: 'Q1 — Long Vowel Patterns', lessons: [
        { title: 'List 1: -ight/-ain', summary: 'Lets learn about special letter patterns that make long vowel sounds! When we see the letters i-g-h-t together like in the word night, they make the long i sound that says its own name. The letters a-i-n together like in the word rain make the long a sound. Look around your room at night with a bright light, or think about walking in the rain on the main street. Now lets practice by clapping each time you hear these sounds in words like flight, train, and pain!' },
        { title: 'List 2: -oat/-eed', summary: 'Today were learning about two special long vowel patterns that make words sound extra clear and strong. When we see -oat at the end of a word like boat or coat, the letter o says its own name with a long sound. The same happens with -eed words like seed or need, where the letter e makes its long sound. Lets practice by acting out these words - pretend to row a boat, put on a coat, plant a seed, or show something you need. Can you think of more -oat and -eed words to add to our list?' },
        { title: 'Origin: "night"', summary: 'The word night comes from a very old word that people spoke long, long ago, and it has kept the same spelling for hundreds of years even though we say it differently now. The letters i-g-h-t work together to make the long i sound, just like in words such as light, bright, and sight. You can practice this pattern by looking outside your window at night and naming all the things you see that rhyme with night, like the bright moonlight or a tall streetlight.' },
      ], questions: [
        { id: '2-SP-Q1-1', q: 'Write a word that rhymes with "light".', type: 'short', answer: 'open' },
        { id: '2-SP-Q1-2', q: '"night" is an ___ word.', type: 'mc', options: ['old English', 'French', 'Spanish'], answer: 0 },
      ]},
      { name: 'Q2 — R-Controlled & Digraphs', lessons: [
        { title: 'List 3: -ar/-or', summary: 'Today were exploring special letter teams called r-controlled vowels where the letter r changes how vowels sound! When you see ar together, it makes the sound you hear in car, star, and park. When you see or together, it makes the sound in for, corn, and horn. The r is like a bossy letter that tells the vowel to make a new sound. Lets practice by clapping when you hear the ar sound in words like barn, yard, and shark, then stomp when you hear the or sound in words like fork, storm, and short!' },
        { title: 'List 4: -th/-wh', summary: 'Today were exploring two special letter teams that make unique sounds! The letters th work together to make the sound you hear at the beginning of think and the end of bath, while wh makes the sound at the start of when and where. These letter pairs are like best friends who always stick together to create their special sounds. Lets practice by saying th-th-th like were thinking hard, then wh-wh-wh like were asking a question, and see if you can spot these letter teams in words around our classroom!' },
        { title: 'Origin: "star"', summary: 'Lets explore the magical r-controlled vowel sound in the word star! When the letter r comes after a vowel, it changes how that vowel sounds. In star, the letter a doesnt say its usual short sound like in cat, but instead makes the special ar sound we hear in words like car, far, and park. You can practice this sound by pretending to be a shining star and saying star words while you twinkle your fingers, listening carefully to how your mouth makes that special ar sound each time.' },
      ], questions: [
        { id: '2-SP-Q2-1', q: 'Which has r-controlled sound?', type: 'mc', options: ['car', 'cat', 'cap'], answer: 0 },
        { id: '2-SP-Q2-2', q: 'Write a word that starts with "wh".', type: 'short', answer: 'open' },
      ]},
      { name: 'Q3 — Compound Words', lessons: [
        { title: 'List 5: sunlight, rainbow, bedroom', summary: 'Today were learning about compound words, which are special words made by putting two smaller words together to make one new word! Lets look at our examples: sunlight is made from sun plus light, rainbow comes from rain plus bow, and bedroom is bed plus room. Can you see how each compound word tells us something about what it means? Now lets play a fun game where you draw pictures showing both parts of each compound word, like drawing the sun and light rays for sunlight, then see if you can think of other compound words around your house like doorbell or toothbrush!' },
        { title: 'List 6: football, notebook, sunlight', summary: 'Today were learning about compound words, which are special words made by putting two smaller words together to make one new word! Lets look at our examples: football is made from foot plus ball, notebook comes from note plus book, and sunlight is made from sun plus light. Can you clap out the two parts in each word? Try saying each compound word slowly and see if you can hear both little words hiding inside the big word!' },
        { title: 'Origin: "sun"', summary: 'The bright sun gives us many wonderful compound words that we use every day! A compound word is made when we put two words together to make one new word, like when we add sun to other words. We can make sunshine by putting sun and shine together, or sunflower by joining sun and flower. Can you think of other sun words like sunset, sunlight, or sunglasses? Try drawing pictures of your favorite sun compound words and see how many you can discover!' },
      ], questions: [
        { id: '2-SP-Q3-1', q: '"rainbow" is a ___ word.', type: 'mc', options: ['compound', 'short', 'foreign'], answer: 0 },
        { id: '2-SP-Q3-2', q: 'Write a compound word (two words joined).', type: 'short', answer: 'open' },
      ]},
      { name: 'Q4 — Review', lessons: [
        { title: 'Master List', summary: 'Lets make a master list together to review all the amazing things weve learned this quarter! A master list is like a big collection that puts everything important in one special place, just like how you might collect all your favorite toys in a treasure box. We can create our own classroom master list by writing down the new words we learned, the fun stories we read, and the exciting math skills we practiced. You can help by sharing one favorite thing you remember from each subject, and well add it to our giant learning list on the board so everyone can see how much weve grown as learners!' },
        { title: 'Word Origins Recap', summary: 'Word Origins Recap helps us remember how words travel from different languages to become part of English! Just like how the word pizza came from Italy and taco came from Mexico, many words we use every day started in other countries long ago. Think about words you know like robot from Czech or ketchup from Chinese - they all have special stories about their journeys! Lets play a fun game where we match everyday words to the countries they came from and discover the amazing adventures our language has been on together.' },
        { title: 'Dictation', summary: 'Dictation is when someone says words out loud and you write them down, just like being a word detective who catches sounds with your pencil! When your teacher says the word cat, you listen carefully to each sound - c-a-t - and write the letters you hear. Lets practice together by listening to simple words like dog, sun, and hat, then writing each letter sound you hear on your paper to spell the complete word.' },
      ], questions: [
        { id: '2-SP-Q4-1', q: 'Write the word: "bright".', type: 'short', answer: 'bright' },
        { id: '2-SP-Q4-2', q: 'A compound word is made of ___', type: 'mc', options: ['two words', 'one letter', 'numbers'], answer: 0 },
      ]},
    ]},
    { name: 'Science', units: [
      { name: 'Q1 — Habitats', lessons: [
        { title: 'Forest & Rainforest', summary: 'Forests are amazing places filled with tall trees that create homes for many animals! In a forest, you might find squirrels jumping from branch to branch, deer eating leaves, and colorful birds singing in the treetops. Rainforests are extra special forests that get lots of rain, making them perfect homes for monkeys, parrots, and even jaguars! Lets pretend to be forest animals - hop like a bunny, swing your arms like a monkey, or flap your wings like a bird while making animal sounds!' },
        { title: 'Ocean & Desert', summary: 'Our amazing Earth has many different homes called habitats where animals and plants live! The ocean is a huge water habitat that covers most of our planet, where colorful fish swim around coral reefs, dolphins play in the waves, and giant whales sing underwater songs. The desert is a very dry and sandy habitat where it rarely rains, so clever animals like camels store water in their bodies, lizards hide under rocks during hot days, and cactus plants save water in their thick stems. Lets pretend to be ocean animals by swimming like fish and making whale sounds, then switch to being desert crea' },
        { title: 'Food Chains', summary: 'Animals need food to grow big and strong, just like you do! A food chain shows us who eats what in nature. It starts with plants that make their own food from sunshine, then goes to animals that eat plants, and finally to animals that eat other animals. For example, grass feeds rabbits, and foxes eat rabbits. You can make your own food chain by drawing pictures of a flower, a butterfly that drinks from it, and a bird that catches the butterfly!' },
      ], questions: [
        { id: '2-SC-Q1-1', q: 'A plant is a ___ in a food chain.', type: 'mc', options: ['producer', 'consumer', 'decomposer'], answer: 0 },
        { id: '2-SC-Q1-2', q: 'Fish live in the ___ habitat.', type: 'mc', options: ['ocean', 'desert', 'forest floor'], answer: 0 },
      ]},
      { name: 'Q2 — Matter & Energy', lessons: [
        { title: 'Properties of Matter', summary: 'Properties of matter are the special things we can notice about different materials around us. Every object has properties like color, size, shape, and texture that help us describe and identify it. For example, a cotton ball is white, soft, and fluffy, while a rock is hard, rough, and heavy. You can explore properties by collecting different items from around your home or classroom and sorting them into groups based on how they feel, look, or sound when you tap them together.' },
        { title: 'Heat & Light', summary: 'Heat and light are special kinds of energy that we can feel and see all around us! The sun gives us both heat that warms our skin and bright light that helps us see during the day. When you rub your hands together really fast, they get warm because youre making heat energy. Light comes from many places like flashlights, candles, and light bulbs that help us see in the dark. Try this fun activity: go outside on a sunny day and put one hand in the sunshine and one hand in the shade, then notice how the hand in the sunlight feels warmer because its getting heat energy from the sun while your ot' },
        { title: 'Simple Machines', summary: 'Simple machines are special tools that help us do work more easily by making heavy things lighter to move or by helping us reach high places. A lever is a simple machine that works like a seesaw - when you use a crowbar to open a box or scissors to cut paper, you are using levers that make the job much easier than using just your hands. You can explore levers at home by using a ruler as a seesaw with small toys, or notice how bottle openers, tweezers, and even your arm work as levers to help you do everyday tasks with less effort.' },
      ], questions: [
        { id: '2-SC-Q2-1', q: 'A lever helps us ___', type: 'mc', options: ['lift heavy things', 'sleep', 'eat'], answer: 0 },
        { id: '2-SC-Q2-2', q: 'The sun gives ___ and light.', type: 'short', answer: 'heat' },
      ]},
      { name: 'Q3 — Earth', lessons: [
        { title: 'Rocks & Soil', summary: 'Our Earth is made of rocks and soil that are all around us! Rocks are hard and can be big like mountains or small like pebbles you find at the park. Soil is the soft brown dirt where plants grow their roots to get food and water. You can explore rocks and soil in your backyard by collecting different colored stones and feeling how the dirt crumbles in your hands when you help plant flowers or vegetables.' },
        { title: 'Water Cycle', summary: 'The water cycle is natures amazing way of moving water around our planet, just like a giant recycling system! When the sun heats up water in oceans, lakes, and rivers, it turns into invisible water vapor that rises up into the sky, kind of like steam from your hot bath. This water vapor forms fluffy clouds, and when the clouds get too heavy with water droplets, they release the water back down as rain or snow. Think about how puddles disappear after a sunny day - that water didnt vanish, it evaporated up to help make new clouds! You can see this cycle in action by putting a clear bowl of wat' },
        { title: 'Weather Tools', summary: 'Weather tools help us learn about the weather around us every day! A thermometer tells us if its hot or cold outside, and a rain gauge measures how much rain falls from the sky. You can make your own weather tools at home by putting a clear cup outside to catch raindrops or checking how the wind moves a ribbon tied to a stick. These simple tools help us understand if we need a jacket, umbrella, or sunscreen when we go outside to play.' },
      ], questions: [
        { id: '2-SC-Q3-1', q: 'Clouds make rain through ___', type: 'mc', options: ['condensation', 'evaporation', 'melting'], answer: 0 },
        { id: '2-SC-Q3-2', q: 'We measure temperature with a ___', type: 'short', answer: 'thermometer' },
      ]},
      { name: 'Q4 — Space', lessons: [
        { title: 'The Solar System', summary: 'The Solar System is like a big family in space with the Sun as the bright parent star and eight planets as its children that travel around it in circles called orbits. Our home planet Earth is one of these special planets, along with others like red Mars and giant Jupiter with its colorful stripes. You can make your own mini solar system by using a flashlight as the Sun and walking in circles around it while holding a small ball to represent Earth moving around our wonderful star.' },
        { title: 'Day & Night', summary: 'Have you ever wondered why it gets dark at night and bright during the day? Our Earth is like a giant spinning ball floating in space, and it takes 24 hours to spin around once! When your side of Earth faces the Sun, you get sunshine and daylight, but when Earth spins so your side faces away from the Sun, it becomes nighttime and you see the Moon and stars instead. You can try this at home by shining a flashlight on a ball and slowly turning it around - watch how one side is bright while the other side stays dark, just like how Earth works! This spinning motion is why we have day and night eve' },
        { title: 'Seasons', summary: 'Our Earth travels around the sun like a spinning top on a long journey that takes one whole year! As Earth moves, different parts get more or less sunlight, which creates our four wonderful seasons. In summer, your part of Earth tilts toward the sun so it gets lots of warm sunshine for swimming and playing outside. In winter, your area tilts away from the sun so it gets less light and becomes cold enough for snow and cozy sweaters. Spring and fall are the in-between seasons when temperatures are just right for planting flowers or jumping in leaf piles. You can make a seasons wheel by drawing p' },
      ], questions: [
        { id: '2-SC-Q4-1', q: 'How many planets orbit the sun?', type: 'mc', options: ['8', '9', '7'], answer: 0 },
        { id: '2-SC-Q4-2', q: 'Earth spins to make ___ and night.', type: 'short', answer: 'day' },
      ]},
    ]},
    { name: 'History & Geography', units: [
      { name: 'Q1 — Native Peoples', lessons: [
        { title: 'First Americans', summary: 'Long, long ago, before your grandparents grandparents were born, the very first people lived in America. These Native peoples were the original Americans who took care of the land for thousands of years. They built homes, grew food like corn and beans, and created beautiful art and stories. Different groups lived in different places - some in forests, some near oceans, and some in deserts. Today we can learn about these amazing first Americans by looking at their pottery, listening to their stories, and visiting museums. Lets draw a picture of a Native American home like a teepee or pueblo a' },
        { title: 'Map Skills', summary: 'Maps are special pictures that show us where places are, just like how Native peoples have always used drawings and special knowledge to find their way around their lands. Long ago, Indigenous families would draw maps in the sand or on bark to show where to find fresh water, good hunting spots, and safe places to camp. You can practice map skills too by drawing a simple map of your classroom, showing where your desk, the door, and your teachers area are located, then use your map to help a friend find different spots in the room.' },
        { title: 'Regions of US', summary: 'Long ago, different groups of Native American people lived all across our big country in different regions or areas, just like how you might live in a city while your cousin lives on a farm. The Inuit people lived in the cold, snowy North where they built igloos, while the Pueblo people lived in the hot, dry Southwest where they made adobe houses from mud and clay. Lets look at a map together and point to where different Native American groups lived, then draw pictures of the different types of homes they built in each region.' },
      ], questions: [
        { id: '2-H-Q1-1', q: 'The ___ were the first people in America.', type: 'mc', options: ['Native Americans', 'Europeans', 'Asians'], answer: 0 },
        { id: '2-H-Q1-2', q: 'Alabama is in the ___ region.', type: 'mc', options: ['South', 'West', 'Northeast'], answer: 0 },
      ]},
      { name: 'Q2 — Explorers', lessons: [
        { title: 'Early Explorers', summary: 'Long ago, brave people called explorers traveled to places no one had ever seen before! They sailed across big oceans and walked through thick forests to discover new lands. Christopher Columbus was a famous explorer who sailed across the Atlantic Ocean and found America. Explorers were very curious and wanted to learn about the world. Lets pretend to be explorers and draw a map of our classroom, marking all the special places we discover like the reading corner and art supplies!' },
        { title: 'Colonies', summary: 'When brave explorers found new lands far from their home countries, they sometimes decided to start colonies, which are like new towns where people from their homeland could come to live and work together. For example, when English explorers came to America, they built a colony called Jamestown where English families could make new homes and grow food. You can pretend to be a colony builder by using blocks or toys to create your own little town with houses, farms, and places where people would work and play together.' },
        { title: 'Thanksgiving', summary: 'Thanksgiving is a special holiday when we remember the brave explorers called Pilgrims who sailed across the ocean to America long ago. Just like when you try something new and scary, the Pilgrims were very brave to start a new life in a faraway place. When they arrived, kind Native Americans helped them learn to grow food and survive. To say thank you, they shared a big feast together with turkey, corn, and pumpkins. Now every November, families gather to eat together and share what they are thankful for, just like those first explorers did. You can be an explorer too by trying new foods at y' },
      ], questions: [
        { id: '2-H-Q2-1', q: 'Explorers came looking for ___', type: 'mc', options: ['new lands and trade', 'the moon', 'gold only'], answer: 0 },
        { id: '2-H-Q2-2', q: 'The first Thanksgiving was shared by two peoples: ___', type: 'mc', options: ['settlers and Native Americans', 'two armies', 'kings'], answer: 0 },
      ]},
      { name: 'Q3 — Government', lessons: [
        { title: 'Community to Country', summary: 'Just like your family has rules to keep everyone safe and happy, communities and countries have rules too! A community is your neighborhood with houses, schools, and parks where people work together to help each other. Many communities join together to make a whole country, like puzzle pieces fitting together to create one big picture. In our country, we have leaders who help make important decisions, just like how your teacher makes rules for your classroom. You can be a good community member by being kind to neighbors, following traffic lights when crossing streets, and taking care of parks ' },
        { title: 'Three Branches', summary: 'Our government has three special groups called branches that work together to help our country, just like how your family has different people with different jobs! The first branch makes the rules we all follow, like laws about wearing seatbelts in cars. The second branch, led by the President, makes sure everyone follows these rules and keeps us safe. The third branch includes judges who help decide if the rules are fair when people disagree. Lets pretend to be each branch - first make a classroom rule, then act like the President explaining it to everyone, and finally be judges deciding if ' },
        { title: 'The Constitution', summary: 'The Constitution is like a big rulebook that tells our country how to work and keeps everyone safe and fair. Just like your classroom has rules about being kind and raising your hand, our whole country has special rules written down long ago that help leaders make good choices and protect all people. Think of it like the rules for a game that everyone agrees to follow so the game is fun and fair for everyone. You can make your own classroom constitution by working together to write down the most important rules that help everyone learn and feel happy at school, then sign your names just like t' },
      ], questions: [
        { id: '2-H-Q3-1', q: 'The President is part of the ___ branch.', type: 'mc', options: ['executive', 'judicial', 'legislative'], answer: 0 },
        { id: '2-H-Q3-2', q: 'Our country’s rule book is the ___', type: 'short', answer: 'Constitution' },
      ]},
      { name: 'Q4 — Alabama', lessons: [
        { title: 'Our State', summary: 'Our state is called Alabama, and its a special place where we live, work, and play together! Alabama has beautiful forests, rivers, and farmland where people grow crops like cotton and peanuts. We can explore our state by visiting places like the Gulf Coast beaches where families swim and build sandcastles, or by learning about the rockets at the Space Center in Huntsville. Lets draw a picture of your favorite Alabama place and share what makes it special to you!' },
        { title: 'State History', summary: 'Alabama has a very special story that goes back thousands of years! Long ago, Native American tribes like the Creek and Cherokee lived here first, building homes and growing corn in the rich soil. Later, people from other places came to Alabama and it became one of the 50 states in 1819. You can visit old forts and museums to see how people lived long ago. Try drawing a picture of what you think an old Alabama village might have looked like with log cabins and gardens!' },
        { title: 'Good Citizens', summary: 'Good citizens are people who help make their community a better place to live. In Alabama, good citizens follow rules, are kind to their neighbors, and take care of their environment. For example, a good citizen might help pick up litter at a local park in Birmingham or share toys with friends at school. You can be a good citizen too by saying please and thank you, helping your family with chores, and being respectful to others. Try this fun activity: draw a picture of yourself doing something helpful in your neighborhood, like watering plants or helping an elderly neighbor carry groceries, th' },
      ], questions: [
        { id: '2-H-Q4-1', q: 'The capital of Alabama is ___', type: 'mc', options: ['Montgomery', 'Birmingham', 'Mobile'], answer: 0 },
        { id: '2-H-Q4-2', q: 'Name one way to be a good citizen.', type: 'short', answer: 'open' },
      ]},
    ]},
    { name: 'Bible & Character', units: [
      { name: 'Q1 — Old Testament Heroes', lessons: [
        { title: 'Moses', summary: 'Moses was a very special helper that God chose to lead His people out of Egypt where they were slaves. When Moses was a baby, his mother put him in a basket on the river to keep him safe, and he was found by a princess who raised him in the palace. When Moses grew up, God spoke to him through a burning bush and asked him to help free the Israelites from the mean king called Pharaoh. Moses was scared because he didnt think he was good enough, but God promised to help him and even let his brother Aaron help him speak to Pharaoh. Lets pretend to be Moses walking with a staff and leading Gods p' },
        { title: 'David', summary: 'David was a young shepherd boy who loved God very much and God loved him too. When a giant named Goliath scared all the big soldiers, brave David trusted God to help him defeat the giant with just a small stone and sling. God made David strong because David believed in Him. David shows us that even when we are small, God can help us do big things when we trust Him. Lets practice being brave like David by standing tall, being kind to others, and remembering that God is always with us to help us face our fears and do what is right.' },
        { title: 'Esther', summary: 'Meet Esther, a brave and beautiful young woman who became a queen! When mean people wanted to hurt Gods people, Queen Esther was scared but she chose to be courageous and ask the king to protect them. Even though she was afraid, she did the right thing because she loved God and His people. God used Esthers bravery to save everyone! Just like Esther, you can be brave when you need to help others or do whats right, even if you feel scared inside.' },
      ], questions: [
        { id: '2-B-Q1-1', q: 'David beat Goliath with a ___', type: 'mc', options: ['sling', 'sword', 'shield'], answer: 0 },
        { id: '2-B-Q1-2', q: 'Esther showed ___ for her people.', type: 'mc', options: ['courage', 'fear', 'anger'], answer: 0 },
      ]},
      { name: 'Q2 — The Psalms', lessons: [
        { title: 'Psalm 23', summary: 'Psalm 23 is a beautiful song about God being like a loving shepherd who takes care of his sheep. Just like a shepherd makes sure his sheep have food, water, and are safe from danger, God takes care of us every day by giving us what we need and keeping us safe. When you feel scared or worried, you can remember that God is always with you like a good shepherd watching over his flock. Lets pretend to be sheep following our shepherd around the room, and talk about all the ways God takes care of us just like families take care of their pets or farmers care for their animals.' },
        { title: 'Praise Songs', summary: 'The Psalms are special songs in the Bible that people sang to show God how much they loved Him, just like when you sing happy birthday or your favorite songs! Some psalms were praise songs where people said wonderful things about God, like how He made the beautiful flowers and takes care of us every day. Other psalms were prayers when people felt sad or scared, and they asked God to help them feel better. King David wrote many of these songs because he loved God so much, and people still sing psalms today in churches all around the world. You can make your own praise song by thinking of all th' },
        { title: 'Trust', summary: 'When we trust someone, we believe they will take care of us and keep us safe, just like how you trust your mom or dad to help you when you need them. The book of Psalms teaches us that we can trust God in the same special way because He loves us so much and always wants whats best for us. King David wrote many psalms about trusting God when he felt scared or worried, and God always helped him feel better and kept him safe. You can practice trusting God too by talking to Him when you feel afraid or need help, just like talking to your best friend who always listens and cares about you.' },
      ], questions: [
        { id: '2-B-Q2-1', q: 'Psalm 23 says "The Lord is my ___".', type: 'mc', options: ['shepherd', 'king', 'teacher'], answer: 0 },
        { id: '2-B-Q2-2', q: 'We praise God by ___', type: 'mc', options: ['singing', 'hiding', 'yelling'], answer: 0 },
      ]},
      { name: 'Q3 — Jesus’ Teachings', lessons: [
        { title: 'The Good Samaritan', summary: 'Jesus told a special story about being kind to everyone, even people who are different from us. A man was hurt on the road, and while others walked by, a kind Samaritan stranger stopped to help him, bandaged his wounds, and took care of him. This teaches us that being a good neighbor means helping anyone who needs us, no matter who they are. Lets practice being good neighbors by drawing a picture of yourself helping someone new at school or in your neighborhood.' },
        { title: 'The Prodigal Son', summary: 'Jesus told a wonderful story about a father who had two sons, and it teaches us about Gods amazing love for us. In the story, the younger son made bad choices and left home, but when he came back feeling sorry, his daddy ran to hug him and threw a big celebration party because he was so happy to have his son home again. This shows us that God is like the loving father - no matter what mistakes we make, God always forgives us and welcomes us back with open arms when we say were sorry. Lets practice saying "Im sorry" to someone today and remember how good it feels to forgive and be forgiven,' },
        { title: 'The Sermon on the Mount', summary: 'Jesus taught many wonderful things to help people be kind and loving. One special time, He sat on a hillside and shared important lessons called the Sermon on the Mount. Jesus told people to be peacemakers, to forgive others, and to treat everyone with kindness just like God treats us. He taught that when we share our toys, help friends who are sad, or say sorry when we make mistakes, we are following Gods way of love. You can practice Jesus teachings by doing one kind act each day, like helping a classmate or giving someone a hug when they need it.' },
      ], questions: [
        { id: '2-B-Q3-1', q: 'The Good Samaritan taught us to love our ___', type: 'mc', options: ['neighbor', 'enemy only', 'self'], answer: 0 },
        { id: '2-B-Q3-2', q: 'The father welcomed his son with ___', type: 'mc', options: ['forgiveness', 'anger', 'silence'], answer: 0 },
      ]},
      { name: 'Q4 — Character', lessons: [
        { title: 'Honesty', summary: 'Honesty means telling the truth even when it might be hard or scary. When you accidentally break something or make a mistake, being honest means you tell a grown-up what really happened instead of hiding it or blaming someone else. Honest people are trustworthy friends because others know they can count on them to be truthful. Lets practice honesty by sharing a time when telling the truth felt difficult but was the right thing to do, and talk about how it made us feel afterward.' },
        { title: 'Forgiveness', summary: 'Forgiveness means saying sorry when we make mistakes and choosing to be kind when someone hurts our feelings. When your friend accidentally breaks your toy, you can forgive them by saying its okay and still being their friend. Sometimes we feel angry or sad, but forgiveness helps our hearts feel better and keeps our friendships strong. Try this: think of someone who said sorry to you, then draw a picture of you two playing together happily to show how forgiveness brings us closer.' },
        { title: 'Service', summary: 'Service means helping others and making our world a better place. When we serve, we use our hands, hearts, and time to care for people around us. A simple act of service might be helping a friend pick up their crayons when they drop them, or helping Mom carry groceries into the house. You can practice service this week by looking for one small way to help someone each day - maybe holding the door open for a classmate, sharing your snack with someone who forgot theirs, or helping your teacher clean up the classroom. Service makes both you and others feel happy and loved.' },
      ], questions: [
        { id: '2-B-Q4-1', q: 'Honesty means ___', type: 'mc', options: ['telling the truth', 'hiding facts', 'bragging'], answer: 0 },
        { id: '2-B-Q4-2', q: 'When someone says sorry, we ___', type: 'mc', options: ['forgive', 'stay mad', 'tell others'], answer: 0 },
      ]},
    ]},
  ])

// ====================== 3RD GRADE (etymology explicit) ======================
export const G3: GradeCurriculum = g('3rd Grade', 3, '8-9', 'Roots of words and numbers take hold.',
  [
    { name: 'Mathematics', units: [
      { name: 'Q1 — Multiplication Mastery', lessons: [
        { title: 'Tables 0-12', summary: 'Welcome to the exciting world of multiplication tables, young mathematicians! Think of multiplication as a super-fast way to count groups of things. When we say 3 times 4, we mean 3 groups of 4 things, which equals 12. For example, if you have 3 bags with 4 cookies each, you have 12 cookies total instead of counting each one. Lets practice by clapping our hands in groups - clap 2 times, then do it 5 times to discover that 2 times 5 equals 10 claps!' },
        { title: 'Word Problems', summary: 'Word problems help us use multiplication in real life! When you see words like groups of, sets of, or rows of, think multiplication. If there are 3 baskets with 2 apples in each basket, we multiply 3 × 2 = 6 apples total. Try this fun activity: look around your classroom and create your own word problems using things you see, like desks in rows or crayons in boxes, then solve them with a friend!' },
        { title: 'Division Intro', summary: 'Division is like sharing things equally among friends! When you have a group of objects and want to split them into smaller, equal groups, youre dividing. Imagine you have 8 cookies and want to share them equally between 2 friends - each friend gets 4 cookies! Try this fun activity: gather 12 toy blocks and practice dividing them into groups of 3. Count how many groups you can make. Division helps us share fairly and solve everyday problems, making it a super useful math skill to learn alongside multiplication.' },
      ], questions: [
        { id: '3-M-Q1-1', q: '7 × 8 = ?', type: 'mc', options: ['54', '56', '49'], answer: 1 },
        { id: '3-M-Q1-2', q: '12 ÷ 3 = ?', type: 'short', answer: '4' },
      ]},
      { name: 'Q2 — Fractions', lessons: [
        { title: 'Numerator & Denominator', summary: 'Hello little mathematicians! A fraction is like sharing something yummy with friends. The bottom number called the denominator tells us how many equal pieces we cut something into, and the top number called the numerator shows how many pieces we take. If we cut a pizza into 4 equal slices and eat 3 pieces, we write it as 3/4 - the 4 means four total slices and the 3 means we ate three of them. Try this fun activity: draw a circle and divide it into 2 equal parts, then color 1 part red to show the fraction 1/2, which means one out of two pieces!' },
        { title: 'Equivalent Fractions', summary: 'Equivalent fractions are different fractions that show the same amount, just like how you can say the same thing in different ways! Think about a yummy chocolate bar split into pieces. If you eat 1 out of 2 pieces, thats the same amount as eating 2 out of 4 pieces or 3 out of 6 pieces - theyre all half the chocolate bar! Lets practice by folding paper circles into different numbers of equal parts and coloring the same amounts to see how fractions can look different but mean the same thing.' },
        { title: 'Compare & Add', summary: 'Lets explore fractions by comparing and adding them together! When we compare fractions, we look at which piece is bigger or smaller. If you have half a pizza and your friend has one-fourth of the same pizza, your half is bigger because it takes up more space. To add fractions with the same bottom number, we simply add the top numbers together. For example, one-fourth plus two-fourths equals three-fourths. Try this fun activity: use paper circles cut into equal pieces to practice comparing different fraction sizes and adding them together by combining the pieces!' },
      ], questions: [
        { id: '3-M-Q2-1', q: '1/2 + 1/4 = ?', type: 'mc', options: ['3/4', '2/6', '1'], answer: 0 },
        { id: '3-M-Q2-2', q: 'Which is bigger: 1/3 or 1/4?', type: 'mc', options: ['1/3', '1/4', 'equal'], answer: 0 },
      ]},
      { name: 'Q3 — Area & Perimeter', lessons: [
        { title: 'Perimeter', summary: 'Perimeter is the distance around the outside edge of a shape, just like walking around the playground fence! If you have a square with sides that are each 3 steps long, you would walk 3 steps, then 3 more steps, then 3 more, and 3 more to get all the way around - thats 12 steps total! Lets practice by using your finger to trace around your desk, a book, or a piece of paper, counting as you go around the edges to find the perimeter.' },
        { title: 'Area', summary: 'Area is how much space something covers, just like how many puzzle pieces fit inside a shape! When you spread out your blanket on the floor, the area is all the space your blanket covers from edge to edge. Think of area like counting squares - if you drew a rectangle and filled it with square stickers, the area would be how many stickers fit inside. Lets try this fun activity: use square blocks or crackers to cover the top of your desk, then count how many squares it takes to fill the whole space - that number tells you the area of your desk!' },
        { title: 'Word Problems', summary: 'Lets solve fun word problems about area and perimeter together! When we find area, we count how many square units fit inside a shape, like counting tiles on a bathroom floor. When we find perimeter, we measure all the way around the outside edges, like walking around a playground fence. Try this: If your bedroom rug is 3 squares long and 2 squares wide, the area is 6 squares total because 3 times 2 equals 6. The perimeter is 10 squares because you walk 3 plus 2 plus 3 plus 2 steps around the edge. Now grab some building blocks and make a rectangle thats 4 blocks long and 3 blocks wide, then ' },
      ], questions: [
        { id: '3-M-Q3-1', q: 'Perimeter of 3×5 rectangle?', type: 'mc', options: ['16', '15', '8'], answer: 0 },
        { id: '3-M-Q3-2', q: 'Area of 3×5 rectangle?', type: 'short', answer: '15' },
      ]},
      { name: 'Q4 — Graphs & Time', lessons: [
        { title: 'Bar & Pictographs', summary: 'Bar graphs and pictographs are fun ways to show information using pictures and bars! A bar graph uses colored bars of different heights to compare things, like how many apples, oranges, and bananas your class likes best. A pictograph uses small pictures or symbols where each picture stands for a certain number, like drawing smiley faces to show how many students are happy each day of the week. Lets make our own pictograph by counting different colored crayons in your box and drawing one crayon symbol for each real crayon you find!' },
        { title: 'Telling Time', summary: 'Learning to tell time is like being a time detective! A clock has two special hands that point to numbers to show us what time it is. The short hand tells us the hour, and the long hand tells us the minutes. When the long hand points to 12 and the short hand points to 3, its 3 oclock - time for a snack! Lets practice by drawing clock faces and moving the hands to show different times throughout your day, like wake-up time, lunch time, and bedtime.' },
        { title: 'Elapsed Time', summary: 'Time is all around us and helps us know how long things take! Elapsed time means how much time passes from when something starts to when it ends, like counting the minutes from when you begin brushing your teeth until you finish. If you start reading at 2:00 and stop at 2:15, then 15 minutes have elapsed. Lets practice by timing how long it takes to sing your favorite song, then look at the clock to see how many minutes passed from start to finish!' },
      ], questions: [
        { id: '3-M-Q4-1', q: 'A bar graph shows ___', type: 'mc', options: ['amounts', 'colors', 'sounds'], answer: 0 },
        { id: '3-M-Q4-2', q: 'From 2:00 to 2:30 is ___ minutes.', type: 'short', answer: '30' },
      ]},
    ]},
    { name: 'Language Arts', units: [
      { name: 'Q1 — Reading', lessons: [
        { title: 'Genres', summary: 'Stories come in different types called genres, just like how toys come in different kinds! Fiction stories are made-up tales with characters like talking animals or magical adventures, while nonfiction books tell us real facts about things like dinosaurs or how plants grow. Poetry uses special words that often rhyme and sound musical when we read them out loud. Lets go on a genre hunt around our classroom library and sort books into three baskets labeled fiction, nonfiction, and poetry to see all the wonderful different types of stories we can explore together!' },
        { title: 'Context Clues', summary: 'When you read and find a word you dont know, you can be a word detective and look for clues around it to figure out what it means! These helpful hints are called context clues. For example, if you read The big elephant used its long trunk to pick up peanuts, you might not know what trunk means, but the sentence tells you its something long that can pick things up, so you can guess its the elephants nose! Lets practice together by reading sentences with tricky words and using the other words around them as our special clues to solve the mystery.' },
        { title: 'Summarize', summary: 'When we summarize a story, we tell the most important parts in just a few sentences, like telling a friend what happened without all the tiny details. If you read about a cat who gets lost but finds its way home by following the smell of fish, your summary might be: A cat got lost and used its nose to find home. Now try summarizing your favorite bedtime story by telling someone the beginning, middle, and end in three short sentences.' },
      ], questions: [
        { id: '3-L-Q1-1', q: 'A story about a real person’s life is a ___', type: 'mc', options: ['biography', 'fable', 'poem'], answer: 0 },
        { id: '3-L-Q1-2', q: 'Context clues help you ___', type: 'mc', options: ['guess a word’s meaning', 'spell', 'count'], answer: 0 },
      ]},
      { name: 'Q2 — Grammar', lessons: [
        { title: 'Plural Nouns', summary: 'Plural nouns are words that tell us about more than one thing! When we have just one cat, we say cat, but when we have many cats, we add an s to make it cats. Most words follow this pattern like dog becomes dogs and book becomes books. Lets practice together by looking around our classroom and naming one pencil, then many pencils, or one friend, then many friends!' },
        { title: 'Verb Tenses', summary: 'Verbs are action words that tell us what someone or something is doing, and they can tell us when something happens too! When we say I jump we mean right now, when we say I jumped we mean it already happened yesterday, and when we say I will jump we mean it will happen tomorrow. Lets practice by acting out different actions - first do them now like I run in place, then pretend you did them yesterday by saying I walked to school, and finally plan for tomorrow by saying I will eat lunch, and notice how the verb words change to show us different times!' },
        { title: 'Comparatives', summary: 'Lets learn about comparatives, which are special words that help us compare two things! When we want to show that one thing is different from another, we add -er to the end of describing words. A cat is small, but a mouse is smaller than the cat. A tree is tall, but a giraffe is taller than the tree. Now you try! Look around the room and find two objects. Can you tell me which one is bigger, smaller, longer, or shorter than the other?' },
      ], questions: [
        { id: '3-L-Q2-1', q: 'Plural of "child"?', type: 'mc', options: ['childs', 'children', 'childes'], answer: 1 },
        { id: '3-L-Q2-2', q: 'Comparative of "small" is ___', type: 'short', answer: 'smaller' },
      ]},
      { name: 'Q3 — Writing', lessons: [
        { title: 'Opinion Paragraph', summary: 'An opinion paragraph tells what you think or feel about something using the word because to explain why. When you write I think cats make the best pets because they are soft and cuddly, you are sharing your opinion with a reason. Try writing about your favorite food, toy, or season and remember to tell why you think that way using because to make your opinion strong and clear.' },
        { title: 'Informative', summary: 'Informative writing teaches others about something you know well by sharing facts and details. When you write to inform, you might explain how to make a sandwich by listing the steps like first get bread, then add peanut butter, and finally add jelly. You could also describe your favorite animal by telling what it looks like, where it lives, and what it eats. Try writing three sentences about your family pet or a toy, sharing interesting facts that would help someone else learn about it.' },
        { title: 'Narrative', summary: 'A narrative is a special kind of story that tells about something that happened with a beginning, middle, and end. When you write a narrative, you share an experience like going to the park, losing a tooth, or having a fun day with friends. You can write about real things that happened to you or make up imaginary adventures with talking animals or magical places. Lets practice by thinking about your best day ever and writing three sentences about what happened first, what happened next, and how it ended.' },
      ], questions: [
        { id: '3-L-Q3-1', q: 'An opinion paragraph needs ___', type: 'mc', options: ['reasons', 'no point', 'only facts'], answer: 0 },
        { id: '3-L-Q3-2', q: 'Write one sentence stating an opinion.', type: 'short', answer: 'open' },
      ]},
      { name: 'Q4 — Cursive & Research', lessons: [
        { title: 'Cursive Intro', summary: 'Welcome to cursive writing, where letters flow together like a beautiful river! Cursive letters are connected and slanted, making writing faster and more elegant than print letters. For example, the letter a starts with a small curve upward, then makes a circle, and ends with a connecting line to the next letter. Lets practice tracing cursive letters in the air with our fingers, starting with simple letters like c, a, and o, then gradually connecting them together to make words.' },
        { title: 'Dictionary Skills', summary: 'Learning to use a dictionary is like having a treasure map to find new words! A dictionary is a special book that tells us what words mean and how to spell them. The words are arranged in alphabetical order, just like the ABC song we know. When we want to know what the word cat means, we look in the C section and find that a cat is a furry animal that says meow. Lets practice by looking up the word dog together and finding out it means a friendly animal that barks and wags its tail!' },
        { title: 'Simple Report', summary: 'In this quarter, well learn how to write a simple report about something we love! A simple report tells facts about a topic in our best cursive handwriting. For example, if you choose dogs as your topic, you might write three sentences like Dogs have four legs, Dogs can be big or small, and Dogs make great pets. First, well pick our favorite animal, toy, or food to research. Then well find three interesting facts by looking at books or asking grown-ups. Finally, well practice writing our facts in beautiful cursive letters to create our very own report to share with the class!' },
      ], questions: [
        { id: '3-L-Q4-1', q: 'Guide words in a dictionary show the ___', type: 'mc', options: ['first and last words on page', 'meaning', 'spelling'], answer: 0 },
        { id: '3-L-Q4-2', q: 'Write one fact you learned this year.', type: 'short', answer: 'open' },
      ]},
    ]},
    { name: 'Spelling & Word Origins', units: [
      { name: 'Q1 — Latin Roots Begin', lessons: [
        { title: 'List 1: -spect/-dict', summary: 'Lets explore two special word parts that come from long ago! The part spect means to look or see, like when you inspect your toys to make sure theyre clean. The part dict means to say or tell, like when you predict what will happen next in a story. Try this fun game: look around your classroom and find three things to inspect closely, then predict out loud what you might find when you look at them carefully!' },
        { title: 'Root: spect = "look"', summary: 'Today we will learn about a special word part called spect that means look! When you see the letters s-p-e-c-t in a word, it has something to do with looking or seeing. The word inspect means to look at something very carefully, like when your teacher inspects your work or when you inspect a cool bug outside. Lets play a looking game where you inspect different objects around our classroom and tell your partner what special details you can see when you look closely at them.' },
        { title: 'Root: dict = "say"', summary: 'The root dict means say, and it helps us understand lots of words we use every day! When you predict what will happen next in a story, you are saying ahead of time what you think might come. A dictionary is a book that says what words mean. Lets play a saying game where you predict what Im thinking by giving clues, then well look up new words in our classroom dictionary together!' },
      ], questions: [
        { id: '3-SP-Q1-1', q: '"inspect" means to look ___ something.', type: 'mc', options: ['at', 'for', 'under'], answer: 0 },
        { id: '3-SP-Q1-2', q: 'The root "dict" means ___', type: 'mc', options: ['say', 'look', 'write'], answer: 0 },
      ]},
      { name: 'Q2 — Greek Roots', lessons: [
        { title: 'List 2: -phone/-graph', summary: 'Lets explore two special word parts that come from long ago! The root phone means sound, like when you talk on a telephone to hear someones voice. The root graph means to write or draw, like when you write your name with a pencil or crayon. Can you think of other phone words like microphone or graph words like photograph? Try drawing a picture while saying phone and graph words out loud to practice both roots together!' },
        { title: 'Root: phone = "sound"', summary: 'The root phone means sound, and you can hear this special word part in many words we use every day! When you talk on a telephone, you are hearing sounds from far away - the phone part means sound. A microphone helps make your voice louder by capturing sound. Even headphones let you listen to sounds privately. Try clapping your hands and saying phone - can you hear how both make sounds? Look around your home with a grown-up and see how many phone words you can find that help us hear or make sounds better.' },
        { title: 'Root: graph = "write"', summary: 'Lets explore the Greek root graph which means write! You can find this special word part in lots of words we use every day. When you see a photograph, youre looking at a picture that light wrote on film. A paragraph is a group of sentences written together. An autograph is when someone writes their name for you. Can you think of other graph words like telegraph or biography? Try drawing pictures of different graph words to help remember that they all connect to writing in some way!' },
      ], questions: [
        { id: '3-SP-Q2-1', q: '"telephone" carries ___ far away.', type: 'mc', options: ['sound', 'light', 'water'], answer: 0 },
        { id: '3-SP-Q2-2', q: '"photograph" means writing with ___', type: 'mc', options: ['light', 'sound', 'hand'], answer: 0 },
      ]},
      { name: 'Q3 — Prefixes', lessons: [
        { title: 'List 3: un-, re-, pre-', summary: 'Today well explore three helpful prefixes that change word meanings! The prefix un- means not, like unhappy means not happy. The prefix re- means again, so reread means to read again. The prefix pre- means before, like preschool happens before regular school. Lets practice by taking turns adding these prefixes to simple words like do, write, and cook to create new words and discover their meanings together!' },
        { title: 'Prefix: un- = "not"', summary: 'The prefix un- is a special word part that we put at the beginning of words to mean not. When we add un- to the word happy, it becomes unhappy, which means not happy or sad. When we add un- to tied, it becomes untied, meaning not tied or loose. Lets practice together by thinking of words that start with un- like unfair, unsafe, or unlock, and figure out what they mean by remembering that un- always means not.' },
        { title: 'Prefix: pre- = "before"', summary: 'The prefix pre means before, and it helps us make new words! When we add pre to the beginning of a word, it tells us something happens before something else. For example, preschool happens before regular school, and preview means to look at something before others see it. Lets play a prefix game - can you think of what preheat means when we talk about an oven, or what prehistoric means when we learn about dinosaurs?' },
      ], questions: [
        { id: '3-SP-Q3-1', q: '"unhappy" means ___', type: 'mc', options: ['not happy', 'very happy', 'happy again'], answer: 0 },
        { id: '3-SP-Q3-2', q: '"preview" means to see it ___', type: 'mc', options: ['before', 'after', 'never'], answer: 0 },
      ]},
      { name: 'Q4 — Review', lessons: [
        { title: 'Master List', summary: 'Our Master List is like a special treasure box where we keep all the important things weve learned together this quarter! Just like how you might have a favorite toy box at home, our Master List holds all our new words, fun facts, and cool discoveries. For example, we might put new vocabulary words like butterfly, addition, or friendship on our list, along with exciting things we learned about animals, numbers, or community helpers. Lets play a fun game where we take turns picking items from our Master List and acting them out or drawing pictures to show what we remember - this helps our bra' },
        { title: 'Root Recap', summary: 'Root Recap time, little gardeners! Remember how plant roots are like hidden underground helpers that drink up water and hold plants steady in the soil? Just like how you use a straw to sip your juice, roots sip water from the dirt to keep plants healthy and strong. Think about the carrots we eat - those orange parts are actually roots that grew big and tasty underground! Now lets pretend to be roots by wiggling our fingers like were reaching deep into the soil to find water for our plant friends.' },
        { title: 'Use Roots', summary: 'Lets use word roots to become word detectives! A root is the main part of a word that gives it meaning, like how tree roots help a tree grow. The root word play helps us understand playground, playful, and player - they all have something to do with playing! Now you try being a word detective - can you find the root word in helpful, helpless, and helper? Look for the part that stays the same in all three words. When you find roots, you unlock the secret to understanding lots of new words!' },
      ], questions: [
        { id: '3-SP-Q4-1', q: 'Write a word with the root "graph".', type: 'short', answer: 'open' },
        { id: '3-SP-Q4-2', q: 'Knowing roots helps you ___ new words.', type: 'mc', options: ['guess the meaning of', 'spell backwards', 'ignore'], answer: 0 },
      ]},
    ]},
    { name: 'Science', units: [
      { name: 'Q1 — Life Science', lessons: [
        { title: 'Plant Parts & Function', summary: 'Plants have special parts that help them live and grow, just like how your body has different parts that help you! The roots grow underground like plant feet to drink up water, the stem stands tall like a backbone to hold the plant up, and the green leaves work like tiny kitchens to make food from sunlight. Pretty flowers help make seeds for new baby plants to grow. Look at a flower outside and see if you can point to each part - can you find the stem holding it up, imagine the roots below the ground, spot the leaves catching sunshine, and admire the colorful petals that will help make seeds f' },
        { title: 'Animal Groups', summary: 'Animals live together in special groups that help them stay safe and find food! Just like you have a family, animals have families too. A group of lions is called a pride, fish swim together in a school, and birds fly in a flock. These animal friends work as a team to protect each other from danger and share yummy meals. Lets play a fun game where you can act out different animal groups - hop like rabbits in a colony, waddle like penguins in a huddle, or buzz around like busy bees in a hive!' },
        { title: 'Adaptations', summary: 'Animals and plants have special features called adaptations that help them live in their homes! A polar bear has thick white fur to stay warm in the snow and hide from other animals. A cactus has thick skin to store water in the desert. Look around your backyard or classroom and find an animal or plant, then draw a picture showing one special feature that helps it survive where it lives.' },
      ], questions: [
        { id: '3-SC-Q1-1', q: 'Leaves make food using ___', type: 'mc', options: ['sunlight', 'moonlight', 'noise'], answer: 0 },
        { id: '3-SC-Q1-2', q: 'A frog is a ___', type: 'mc', options: ['amphibian', 'mammal', 'bird'], answer: 0 },
      ]},
      { name: 'Q2 — Forces', lessons: [
        { title: 'Push, Pull, Friction', summary: 'Push, pull, and friction are forces that help us move things every day! A push moves something away from you, like when you push a swing or roll a ball across the floor. A pull brings something closer to you, like when you pull a wagon or tug on a rope. Friction is a special force that happens when things rub together and makes them slow down or stop, like when you slide down a playground slide or rub your hands together to make them warm. Try this fun activity: find a toy car and push it gently across different surfaces like carpet, wood, and sandpaper, then notice how friction makes it go fa' },
        { title: 'Magnets', summary: 'Magnets are special objects that can pull some things toward them without even touching them! This invisible pulling power is called a magnetic force. You might have magnets on your refrigerator at home that hold up your artwork or shopping lists. Magnets love to stick to things made of iron and steel, like paper clips, coins, or metal spoons, but they cannot pull plastic toys, wooden blocks, or paper. Try this fun experiment with a grown-up: gather different objects from around your house like a metal spoon, a plastic cup, a paper clip, and a crayon, then use a magnet to test which items get ' },
        { title: 'Gravity', summary: 'Gravity is a special invisible force that pulls everything down toward the ground, just like a gentle giant giving everything a hug toward Earth. When you drop your toy or jump up high, gravity brings you and your toy back down safely. You can explore gravity by dropping different objects like a feather, a ball, and a block from the same height and watching how they all fall down, but some might fall faster than others because of their shape and weight.' },
      ], questions: [
        { id: '3-SC-Q2-1', q: 'Gravity pulls things ___', type: 'mc', options: ['down', 'up', 'sideways'], answer: 0 },
        { id: '3-SC-Q2-2', q: 'Opposite magnet poles ___', type: 'mc', options: ['attract', 'repel', 'do nothing'], answer: 0 },
      ]},
      { name: 'Q3 — Weather', lessons: [
        { title: 'Cloud Types', summary: 'Clouds are like fluffy cotton balls floating in the sky that come in different shapes and sizes. Cumulus clouds look puffy and white like cotton candy, stratus clouds stretch across the sky like a gray blanket, and cirrus clouds are wispy and thin like feathers up high. You can be a cloud spotter by going outside and looking up to see which types of clouds are in the sky today, then draw pictures of what you see and share them with your class.' },
        { title: 'Fronts', summary: 'A weather front is like a big invisible wall in the sky where warm air and cold air meet and push against each other. When a cold front moves through your town, it brings cooler temperatures and sometimes storms with rain or snow, while a warm front brings warmer weather and gentle rain. You can be a weather detective by watching the clouds change and feeling if the air gets warmer or cooler during the day, then draw pictures of what the sky looks like before and after the weather changes.' },
        { title: 'Climate', summary: 'Climate is the kind of weather a place has most of the time during the whole year. Some places like Florida are usually warm and sunny, while places like Alaska are usually cold and snowy. Your town has its own climate too! Ask a grown-up what kind of weather your area has in summer, winter, spring, and fall, then draw a picture showing your favorite season and what you like to wear and do during that time of year.' },
      ], questions: [
        { id: '3-SC-Q3-1', q: 'Cumulus clouds look like ___', type: 'mc', options: ['fluffy cotton', 'thin lines', 'flat gray'], answer: 0 },
        { id: '3-SC-Q3-2', q: 'Climate is weather over a ___ time.', type: 'mc', options: ['long', 'short', 'single day'], answer: 0 },
      ]},
      { name: 'Q4 — Solar System', lessons: [
        { title: 'Planets Order', summary: 'Lets learn about the eight planets in our solar system and their special order from the sun! The planets line up like friends in a row, starting with tiny Mercury closest to the hot sun, then Venus, our home Earth, red Mars, giant Jupiter, beautiful Saturn with rings, cold Uranus, and faraway Neptune at the end. Think of it like eight different sized balls arranged from smallest to biggest in some places! You can remember their order by making up a silly sentence using the first letter of each planets name, like My Very Excited Mom Just Served Us Nachos, or try arranging different sized toys' },
        { title: 'Moon Phases', summary: 'Look up at the night sky and you might see the moon looking different each time! Sometimes the moon looks like a big bright circle, sometimes like a half cookie, and sometimes like a skinny banana smile. These different shapes are called moon phases, and they happen because the sun shines on different parts of the moon as it moves around Earth. Just like when you shine a flashlight on a ball and see only part of it lit up, the moon shows us different amounts of its bright side throughout the month. You can be a moon detective by looking outside each night and drawing what shape the moon looks ' },
        { title: 'Stars', summary: 'Stars are giant balls of hot, glowing gas that shine brightly in the night sky, just like our Sun which is actually a star too! When you look up at night, you might see thousands of twinkling stars that seem tiny because they are so far away from Earth. You can practice being a star scientist by going outside on a clear night with a grown-up and counting how many stars you can see, or even try to find star patterns called constellations that look like pictures in the sky.' },
      ], questions: [
        { id: '3-SC-Q4-1', q: 'The 3rd planet from the sun is ___', type: 'mc', options: ['Earth', 'Mars', 'Venus'], answer: 0 },
        { id: '3-SC-Q4-2', q: 'Our sun is a ___', type: 'mc', options: ['star', 'planet', 'moon'], answer: 0 },
      ]},
    ]},
    { name: 'History & Geography', units: [
      { name: 'Q1 — Colonies to Independence', lessons: [
        { title: '13 Colonies', summary: 'Long ago, people from England came across the big ocean to start new homes in America and made 13 special places called colonies, just like how you might build 13 different neighborhoods with houses and stores. One famous colony was called Virginia where people grew tobacco plants, and another was Massachusetts where children went to some of the first schools in America. Lets count to 13 together and name something special about our own neighborhood for each number we say!' },
        { title: 'Revolution', summary: 'A revolution is when people decide they want big changes and work together to make them happen. Long ago, the American colonists were unhappy because they had to follow rules made by a king who lived far away in England, and they wanted to make their own rules instead. The colonists worked together and fought to become free, and thats how America became its own country. You can pretend to have your own revolution by gathering your friends and deciding together on new, fair rules for your playground games.' },
        { title: 'Declaration', summary: 'The Declaration of Independence was a very important letter that told everyone America wanted to be its own country instead of belonging to England. Think of it like when you tell your parents you want to make your own choices about what to wear or eat because you are growing up and can take care of yourself. The brave men who wrote this special paper in 1776 wanted America to have its own rules and leaders. You can practice being independent too by helping make decisions at home, like choosing healthy snacks or picking out books to read, just like America chose to make its own decisions as a ' },
      ], questions: [
        { id: '3-H-Q1-1', q: 'The Declaration of Independence was in ___', type: 'mc', options: ['1776', '1492', '1865'], answer: 0 },
        { id: '3-H-Q1-2', q: 'The colonists wanted ___', type: 'mc', options: ['freedom', 'more taxes', 'a king'], answer: 0 },
      ]},
      { name: 'Q2 — Westward', lessons: [
        { title: 'Lewis & Clark', summary: 'Long ago, two brave explorers named Lewis and Clark went on an amazing adventure to see what was in the western part of our big country. President Jefferson asked them to walk and canoe thousands of miles to discover new lands, animals, and plants that no one back east had ever seen before. They met friendly Native American people who helped show them the way, and they saw huge mountains, rushing rivers, and even the ocean at the end of their journey. Just like when you explore your backyard or neighborhood park, Lewis and Clark kept journals to draw pictures and write about all the exciting n' },
        { title: 'Trail & Pioneers', summary: 'Long ago, brave families called pioneers packed their wagons and traveled west on special paths called trails to find new homes and better lives. The famous Oregon Trail was like a dirt highway that stretched for over 2,000 miles, where pioneers walked alongside their covered wagons pulled by oxen for months, facing rivers to cross, mountains to climb, and storms along the way. Lets pretend to be pioneers and pack our classroom wagon with items we think families would need for their long journey west, like food, tools, and warm blankets.' },
        { title: 'Native Displacement', summary: 'Long ago, Native American families had lived on the land for many, many years before other people came to America. When new settlers moved west looking for places to build homes and farms, they often took the land where Native families already lived. This meant Native American people had to leave their homes and move to new places, which made them very sad because they loved their land. The Cherokee people, for example, had to walk very far from their homes to a new place, and this long, difficult journey is remembered as a very sad time. To help us understand how this felt, lets try an activ' },
      ], questions: [
        { id: '3-H-Q2-1', q: 'Lewis and Clark ___ the west.', type: 'mc', options: ['explored', 'ruled', 'sold'], answer: 0 },
        { id: '3-H-Q2-2', q: 'Pioneers moved ___', type: 'mc', options: ['west', 'east', 'north only'], answer: 0 },
      ]},
      { name: 'Q3 — Civil War', lessons: [
        { title: 'Causes', summary: 'A long time ago, people in our country had big disagreements about how to treat other people fairly. Some states thought it was okay to make people work without paying them, but other states said that was very wrong and mean. These disagreements made people so upset that they started fighting, which became the Civil War. Think about when you and your friend disagree about sharing toys - sometimes it makes you both very angry! Lets draw a picture of two groups of people talking about their different ideas to help us understand how disagreements can grow bigger and bigger.' },
        { title: 'Key Figures', summary: 'The Civil War had many important people who helped shape our countrys history. Abraham Lincoln was the President who wanted to keep America together and help free enslaved people. Ulysses Grant was a brave general who led the Union army to victory. On the other side, Robert E. Lee was a skilled Confederate general. These leaders made big decisions that changed America forever. Lets draw pictures of these three important figures and talk about how they each played different roles in this important time in our nations story.' },
        { title: 'Emancipation', summary: 'During the Civil War, President Abraham Lincoln made an important decision called the Emancipation Proclamation that said enslaved people in certain states should be free. This was like opening a cage door for birds who had been trapped inside. Many brave enslaved people had already been escaping to freedom, and this proclamation helped more people become free. You can pretend to be President Lincoln by writing your own proclamation about something important, like declaring that all toys should be shared fairly or that everyone deserves kindness.' },
      ], questions: [
        { id: '3-H-Q3-1', q: 'Abraham Lincoln was the ___ president.', type: 'mc', options: ['16th', '1st', '20th'], answer: 0 },
        { id: '3-H-Q3-2', q: 'The Civil War ended ___', type: 'mc', options: ['slavery', 'taxes', 'war with France'], answer: 0 },
      ]},
      { name: 'Q4 — Maps & Globe Skills', lessons: [
        { title: 'Latitude/Longitude', summary: 'Have you ever wondered how we can find any place on Earth? Our planet has special invisible lines called latitude and longitude that work like a giant grid to help us locate places! Latitude lines go around the Earth from east to west, like belts around a ball, while longitude lines go from the North Pole to the South Pole, like slices of an orange. Think of your classroom - you might sit in the third row and fifth seat, which helps your teacher find you quickly. Earth works the same way! For example, your school has its own special latitude and longitude numbers that tell exactly where it is ' },
        { title: 'Hemispheres', summary: 'Lets discover hemispheres together! A hemisphere is like cutting our round Earth in half, just like slicing an orange. The equator is an imaginary line that goes around the middle of Earth and splits it into two halves called the Northern Hemisphere and Southern Hemisphere. If you live in the United States, youre in the Northern Hemisphere with countries like Canada. Australia and Antarctica are in the Southern Hemisphere. Try this fun activity: take a ball or orange and draw a line around the middle with your finger - now youve made two hemispheres just like Earth!' },
        { title: 'US Physical', summary: 'The United States has many different types of land and water that we can see on maps and globes. Mountains are very tall land that reaches up to the sky, like the Rocky Mountains in the west. Rivers are long streams of water that flow across the land, such as the Mississippi River that runs down the middle of our country. Oceans are huge bodies of water that surround parts of America, like the Atlantic Ocean on the east side. Lets look at a map of the United States together and use our fingers to trace the mountains, follow the rivers, and point to the oceans we can find.' },
      ], questions: [
        { id: '3-H-Q4-1', q: 'Lines that run east-west are ___', type: 'mc', options: ['latitude', 'longitude', 'rivers'], answer: 0 },
        { id: '3-H-Q4-2', q: 'We are in the ___ hemisphere.', type: 'mc', options: ['Northern', 'Southern', 'Eastern'], answer: 0 },
      ]},
    ]},
    { name: 'Bible & Character', units: [
      { name: 'Q1 — Joseph', lessons: [
        { title: 'Sold & Sold Again', summary: 'Josephs big brothers were very mean to him and sold him to some traders who were traveling far away, just like when you might trade your toy with a friend but Joseph didnt want to be traded at all. When Joseph got to Egypt, the traders sold him again to a man named Potiphar to be his helper, which made Joseph very sad because he missed his family so much. Even though scary and sad things happened to Joseph, God was still taking care of him and had a special plan, just like how your parents still love you even when bad things happen. Lets act out being kind helpers like Joseph was, and remem' },
        { title: 'Forgives Brothers', summary: 'Do you know what forgiveness means? Its when someone hurts your feelings but you choose to love them anyway and not stay mad. Joseph had brothers who were very mean to him and sold him far away from home. But when Joseph saw them again many years later, he forgave them because he loved them. Joseph could have been angry, but instead he hugged his brothers and was kind to them. Think of a time when someone wasnt nice to you - maybe they took your toy or said something mean. You can be like Joseph and choose to forgive them! Lets practice by drawing a picture of yourself being kind to someone' },
        { title: 'God’s Care', summary: 'God loves us and takes care of us just like He took care of Joseph! When Joseph was sold by his brothers and taken far from home, he felt scared and alone, but God stayed with him every single day and helped him become a leader in Egypt. Even when bad things happened, God had a special plan to use Joseph to save many people from hunger. Just like God watched over Joseph, He watches over you too and has wonderful plans for your life! Lets draw a picture of how God takes care of you every day, like giving you food, family, friends, and keeping you safe.' },
      ], questions: [
        { id: '3-B-Q1-1', q: 'Joseph forgave his ___', type: 'mc', options: ['brothers', 'friends', 'king'], answer: 0 },
        { id: '3-B-Q1-2', q: 'God turned bad into ___', type: 'mc', options: ['good', 'nothing', 'worse'], answer: 0 },
      ]},
      { name: 'Q2 — Parables', lessons: [
        { title: 'Sower', summary: 'Jesus told a wonderful story about a farmer who planted seeds to help us understand how Gods love grows in our hearts. In the story, some seeds fell on good soil and grew into beautiful plants, just like when we listen to Gods teachings and let them help us become kind and loving people. Lets pretend to be farmers and plant pretend seeds while we think about how we can let Gods love grow in us by being helpful to our friends and family.' },
        { title: 'Talents', summary: 'God gives each of us special gifts called talents, just like how some friends are great at singing while others are amazing at being kind or helping others. When we use our talents to help people and make them happy, it makes God smile too. Lets play a fun game where we act out different talents like drawing, dancing, or being a good friend, and see how many wonderful gifts God has given our class to share with the world around us.' },
        { title: 'Mustard Seed', summary: 'Jesus told a story about a tiny mustard seed that grows into a big, beautiful tree where birds can build their nests. Even though the seed is so small you can barely see it, it becomes huge and helps many creatures! Gods love works the same way - it starts small in our hearts but grows bigger and bigger until we can share it with everyone around us. Just like when you show kindness to one friend, then another friend sees it and wants to be kind too, and soon your whole class is being extra nice to each other! Lets plant some seeds in cups and watch them grow while we remember how Gods love ' },
      ], questions: [
        { id: '3-B-Q2-1', q: 'The man with many talents was ___', type: 'mc', options: ['praised', 'punished', 'ignored'], answer: 0 },
        { id: '3-B-Q2-2', q: 'A mustard seed is ___ but grows big.', type: 'mc', options: ['small', 'large', 'round'], answer: 0 },
      ]},
      { name: 'Q3 — Psalms & Proverbs', lessons: [
        { title: 'Proverbs on Words', summary: 'God wants us to use our words to help and encourage others, just like how kind words make us feel happy inside. When we say nice things like "thank you" or "you did a great job," we make people smile and feel loved. Lets practice saying three kind words to someone in our family today and see how it makes them feel!' },
        { title: 'Fear the Lord', summary: 'The Bible teaches us to "fear the Lord," which doesnt mean being scared of God like a monster, but showing Him special respect and honor because He is so wonderful and powerful. Just like how we show respect to our parents or teachers by listening carefully and obeying, we show respect to God by loving Him and following His ways. When we fear the Lord, we remember that God made everything beautiful around us and loves us very much. Lets practice showing respect to God by sitting quietly for a moment, folding our hands, and thinking about how amazing God is and thanking Him for all the good t' },
        { title: 'Trust', summary: 'Trust means believing that God will take care of you, just like how you trust your mom or dad to keep you safe. When King David was scared, he remembered that God was always with him, watching over him like a loving parent. You can trust God too when you feel worried or afraid. Lets practice trusting by closing our eyes, taking deep breaths, and remembering that God loves us so much and will never leave us alone.' },
      ], questions: [
        { id: '3-B-Q3-1', q: 'Wisdom begins with ___ the Lord.', type: 'mc', options: ['respecting', 'fearing', 'ignoring'], answer: 1 },
        { id: '3-B-Q3-2', q: 'Kind words are like a ___', type: 'mc', options: ['healing tree', 'stone', 'storm'], answer: 0 },
      ]},
      { name: 'Q4 — Missions', lessons: [
        { title: 'Tell Others', summary: 'God wants us to tell other people about Jesus because He loves everyone so much! Just like when you have exciting news about a fun day at the park, you want to share it with your friends and family. We can tell others about Jesus by being kind, helping someone who is sad, or simply saying that Jesus loves them. Think of someone in your class or neighborhood who might not know about Jesus - you could invite them to church with you, share a Bible story, or show them Gods love by sharing your toys or giving them a hug when they need it.' },
        { title: 'Help the Poor', summary: 'Jesus wants us to help people who dont have enough food, clothes, or toys. When we share our lunch with a hungry friend or give our old toys to children who need them, we show Gods love. This week, lets collect canned food for families in our neighborhood or draw cheerful pictures to give to people who might be sad and lonely.' },
        { title: 'My Part', summary: 'God wants every person to know about Jesus, and even though you are young, you have an important part in sharing His love! You can be a missionary right where you are by being kind to friends at school, helping your family, and telling others about Jesus when you pray before meals or invite someone to church. This week, think of one person who doesnt know Jesus and pray for them every day, then ask God to show you how to be extra kind to them so they can see Jesus love through you.' },
      ], questions: [
        { id: '3-B-Q4-1', q: 'We share the good news by ___', type: 'mc', options: ['telling others', 'hiding', 'bragging'], answer: 0 },
        { id: '3-B-Q4-2', q: 'God cares especially for the ___', type: 'mc', options: ['needy', 'rich only', 'strong'], answer: 0 },
      ]},
    ]},
  ])

// 4th and 5th grades continue in curriculum_part2b.ts (kept lean for compile speed)
export const CURRICULUM_PART2: GradeCurriculum[] = [G2, G3]
