/**
 * Diploma Exam Question Bank (~200 questions)
 * Adult high-school-equivalency style: Math, English, Science, Social Studies, Life Skills
 * Subjects: math | english | science | social_studies | life_skills
 */

export type DiplomaSubject = 'math' | 'english' | 'science' | 'social_studies' | 'life_skills'

export interface DiplomaQuestion {
  id: string
  subject: DiplomaSubject
  question: string
  options: string[]
  correctIndex: number
  level: number
}

export const DIPLOMA_QUESTIONS: DiplomaQuestion[] = [
  { id: 'd1', subject: 'math', question: "What is 15% of 200?", options: ["25", "30", "35", "40"], correctIndex: 1, level: 11 },
  { id: 'd2', subject: 'math', question: "Solve: 3x + 7 = 22. What is x?", options: ["3", "5", "7", "9"], correctIndex: 1, level: 11 },
  { id: 'd3', subject: 'math', question: "What is 0.25 as a fraction in simplest form?", options: ["1/4", "1/2", "1/3", "2/5"], correctIndex: 0, level: 11 },
  { id: 'd4', subject: 'math', question: "A shirt costs $40 and is 25% off. What is the sale price?", options: ["$30", "$32", "$35", "$28"], correctIndex: 0, level: 11 },
  { id: 'd5', subject: 'math', question: "What is 7/8 - 3/8?", options: ["1/2", "1/4", "4/8", "3/4"], correctIndex: 1, level: 11 },
  { id: 'd6', subject: 'math', question: "Round 47.68 to the nearest whole number.", options: ["47", "48", "50", "46"], correctIndex: 1, level: 11 },
  { id: 'd7', subject: 'math', question: "What is 12 squared (12^2)?", options: ["124", "144", "122", "156"], correctIndex: 1, level: 11 },
  { id: 'd8', subject: 'math', question: "A car travels 60 miles in 1.5 hours. What is its average speed?", options: ["30 mph", "40 mph", "45 mph", "50 mph"], correctIndex: 1, level: 11 },
  { id: 'd9', subject: 'math', question: "What is the area of a rectangle 8 ft by 5 ft?", options: ["35 sq ft", "40 sq ft", "45 sq ft", "13 sq ft"], correctIndex: 1, level: 11 },
  { id: 'd10', subject: 'math', question: "Convert 3/4 to a percent.", options: ["25%", "50%", "75%", "80%"], correctIndex: 2, level: 11 },
  { id: 'd11', subject: 'math', question: "What is 2 cubed (2^3)?", options: ["6", "8", "9", "12"], correctIndex: 1, level: 11 },
  { id: 'd12', subject: 'math', question: "If a recipe needs 2 cups for 4 people, how many for 10 people?", options: ["4", "5", "6", "8"], correctIndex: 1, level: 11 },
  { id: 'd13', subject: 'math', question: "What is the prime factorization of 12?", options: ["2x6", "2^2x3", "3x4", "2x2x3x3"], correctIndex: 1, level: 11 },
  { id: 'd14', subject: 'math', question: "Solve: 5y - 3 = 17.", options: ["2", "4", "5", "6"], correctIndex: 1, level: 11 },
  { id: 'd15', subject: 'math', question: "What is 1/2 + 1/3?", options: ["2/5", "5/6", "1", "2/3"], correctIndex: 1, level: 11 },
  { id: 'd16', subject: 'math', question: "A 20% tip on a $65 bill is?", options: ["$11", "$13", "$15", "$20"], correctIndex: 1, level: 11 },
  { id: 'd17', subject: 'math', question: "What is the perimeter of a square with side 9 cm?", options: ["18 cm", "27 cm", "36 cm", "81 cm"], correctIndex: 2, level: 11 },
  { id: 'd18', subject: 'math', question: "What is 144 / 12?", options: ["11", "12", "13", "14"], correctIndex: 1, level: 11 },
  { id: 'd19', subject: 'math', question: "Which is the largest: 0.45, 0.5, 0.405, 0.54?", options: ["0.45", "0.5", "0.405", "0.54"], correctIndex: 3, level: 11 },
  { id: 'd20', subject: 'math', question: "What is 3/5 as a decimal?", options: ["0.35", "0.6", "0.35", "0.75"], correctIndex: 1, level: 11 },
  { id: 'd21', subject: 'math', question: "If x = 4, what is 2x + 3x?", options: ["14", "20", "24", "12"], correctIndex: 1, level: 11 },
  { id: 'd22', subject: 'math', question: "What is 25 x 40?", options: ["1000", "900", "800", "1100"], correctIndex: 0, level: 11 },
  { id: 'd23', subject: 'math', question: "A triangle has angles 50 and 60. What is the third angle?", options: ["60", "70", "80", "90"], correctIndex: 1, level: 11 },
  { id: 'd24', subject: 'math', question: "What is the median of 3, 7, 9, 12, 15?", options: ["7", "9", "12", "10"], correctIndex: 1, level: 11 },
  { id: 'd25', subject: 'math', question: "Simplify: 4(2 + 3) - 5.", options: ["15", "20", "12", "11"], correctIndex: 0, level: 11 },
  { id: 'd26', subject: 'math', question: "What is 1 kilometer in meters?", options: ["10", "100", "1000", "10000"], correctIndex: 2, level: 11 },
  { id: 'd27', subject: 'math', question: "A pack of 6 costs $4.20. Cost per item?", options: ["$0.60", "$0.70", "$0.80", "$1.00"], correctIndex: 1, level: 11 },
  { id: 'd28', subject: 'math', question: "What is 2/3 of 90?", options: ["30", "45", "60", "75"], correctIndex: 2, level: 11 },
  { id: 'd29', subject: 'math', question: "Solve: 8 - 2(3 + 1).", options: ["0", "2", "4", "8"], correctIndex: 0, level: 11 },
  { id: 'd30', subject: 'math', question: "What is the next number: 2, 4, 8, 16, ?", options: ["24", "28", "32", "30"], correctIndex: 2, level: 11 },
  { id: 'd31', subject: 'math', question: "What is 5! (5 factorial)?", options: ["25", "60", "120", "100"], correctIndex: 2, level: 11 },
  { id: 'd32', subject: 'math', question: "Convert 0.125 to a fraction.", options: ["1/8", "1/5", "1/10", "1/4"], correctIndex: 0, level: 11 },
  { id: 'd33', subject: 'math', question: "A $200 item is marked up 10%. New price?", options: ["$210", "$220", "$230", "$205"], correctIndex: 0, level: 11 },
  { id: 'd34', subject: 'math', question: "What is the square root of 169?", options: ["11", "12", "13", "14"], correctIndex: 2, level: 11 },
  { id: 'd35', subject: 'math', question: "If 3 apples cost $1.50, how much do 10 cost?", options: ["$4", "$5", "$6", "$7"], correctIndex: 1, level: 11 },
  { id: 'd36', subject: 'math', question: "What is 7/10 - 2/5?", options: ["3/10", "1/2", "2/5", "1/10"], correctIndex: 0, level: 11 },
  { id: 'd37', subject: 'math', question: "A bus leaves at 2:45 PM and travels 2h 20m. Arrival?", options: ["5:05 PM", "4:65 PM", "5:00 PM", "4:55 PM"], correctIndex: 0, level: 11 },
  { id: 'd38', subject: 'math', question: "What is 15 x 15?", options: ["225", "215", "235", "250"], correctIndex: 0, level: 11 },
  { id: 'd39', subject: 'math', question: "Probability of rolling a 3 on a fair die?", options: ["1/6", "1/3", "1/2", "1/4"], correctIndex: 0, level: 11 },
  { id: 'd40', subject: 'math', question: "What is the mode of 2,4,4,6,8?", options: ["2", "4", "6", "8"], correctIndex: 1, level: 11 },
  { id: 'd41', subject: 'math', question: "Solve: x/4 = 5.", options: ["9", "20", "1", "15"], correctIndex: 1, level: 11 },
  { id: 'd42', subject: 'english', question: "Which word is a noun?", options: ["run", "blue", "cat", "quickly"], correctIndex: 2, level: 11 },
  { id: 'd43', subject: 'english', question: "Choose the correctly spelled word.", options: ["recieve", "receive", "receve", "receeve"], correctIndex: 1, level: 11 },
  { id: 'd44', subject: 'english', question: "What is the plural of 'child'?", options: ["childs", "children", "childes", "childer"], correctIndex: 1, level: 11 },
  { id: 'd45', subject: 'english', question: "Identify the verb: 'The dog barked loudly.'", options: ["dog", "loudly", "barked", "the"], correctIndex: 2, level: 11 },
  { id: 'd46', subject: 'english', question: "Which is a synonym for 'happy'?", options: ["sad", "joyful", "angry", "tired"], correctIndex: 1, level: 11 },
  { id: 'd47', subject: 'english', question: "Choose the correct homophone: 'They ___ going home.'", options: ["there", "their", "they're", "thier"], correctIndex: 2, level: 11 },
  { id: 'd48', subject: 'english', question: "What does 'benevolent' mean?", options: ["kind", "cruel", "lazy", "smart"], correctIndex: 0, level: 11 },
  { id: 'd49', subject: 'english', question: "Which sentence is grammatically correct?", options: ["Him went to the store.", "He went to the store.", "He go to the store.", "Him go store."], correctIndex: 1, level: 11 },
  { id: 'd50', subject: 'english', question: "What is the antonym of 'expand'?", options: ["grow", "contract", "increase", "spread"], correctIndex: 1, level: 11 },
  { id: 'd51', subject: 'english', question: "Identify the adjective: 'The red ball bounced.'", options: ["red", "ball", "bounced", "the"], correctIndex: 0, level: 11 },
  { id: 'd52', subject: 'english', question: "What is the main idea of a paragraph?", options: ["the last sentence", "the central point", "a random detail", "the title"], correctIndex: 1, level: 11 },
  { id: 'd53', subject: 'english', question: "Choose the correct punctuation: 'Wow___ that was amazing!'", options: [".", ",", "!", "?"], correctIndex: 2, level: 11 },
  { id: 'd54', subject: 'english', question: "Which word is a preposition?", options: ["under", "happy", "quickly", "cat"], correctIndex: 0, level: 11 },
  { id: 'd55', subject: 'english', question: "What does 'anonymous' mean?", options: ["famous", "nameless", "angry", "old"], correctIndex: 1, level: 11 },
  { id: 'd56', subject: 'english', question: "'Their going to the park' is incorrect because:", options: ["spelling", "should be 'they're'", "wrong verb", "missing period"], correctIndex: 1, level: 11 },
  { id: 'd57', subject: 'english', question: "Which is a compound word?", options: ["sunflower", "running", "green", "book"], correctIndex: 0, level: 11 },
  { id: 'd58', subject: 'english', question: "What is a metaphor?", options: ["a literal comparison", "a figure of speech implying equality", "a question", "a list"], correctIndex: 1, level: 11 },
  { id: 'd59', subject: 'english', question: "Choose the correct form: 'She ___ to school yesterday.'", options: ["go", "goes", "went", "going"], correctIndex: 2, level: 11 },
  { id: 'd60', subject: 'english', question: "What does the prefix 'un-' mean?", options: ["again", "not", "before", "after"], correctIndex: 1, level: 11 },
  { id: 'd61', subject: 'english', question: "Which is a run-on sentence?", options: ["I went home.", "I went home and I ate.", "I went home I ate dinner."], correctIndex: 2, level: 11 },
  { id: 'd62', subject: 'english', question: "Identify the pronoun: 'Maria said she would come.'", options: ["Maria", "said", "she", "would"], correctIndex: 2, level: 11 },
  { id: 'd63', subject: 'english', question: "What is the past tense of 'write'?", options: ["writed", "wrote", "written", "writ"], correctIndex: 1, level: 11 },
  { id: 'd64', subject: 'english', question: "Which word means 'to make something clear'?", options: ["confuse", "clarify", "complicate", "blur"], correctIndex: 1, level: 11 },
  { id: 'd65', subject: 'english', question: "'The silence was deafening' is an example of:", options: ["irony", "simile", "metaphor", "alliteration"], correctIndex: 0, level: 11 },
  { id: 'd66', subject: 'english', question: "Choose the correct word: 'I ___ my keys on the table.'", options: ["lay", "lie", "laid", "lying"], correctIndex: 2, level: 11 },
  { id: 'd67', subject: 'english', question: "What is the plural of 'mouse'?", options: ["mouses", "mice", "meese", "mouses"], correctIndex: 1, level: 11 },
  { id: 'd68', subject: 'english', question: "Which sentence uses a comma correctly?", options: ["John who is tall left.", "John, who is tall, left.", "John who is tall, left."], correctIndex: 1, level: 11 },
  { id: 'd69', subject: 'english', question: "What does 'inevitable' mean?", options: ["avoidable", "certain to happen", "unlikely", "optional"], correctIndex: 1, level: 11 },
  { id: 'd70', subject: 'english', question: "Identify the adverb: 'He spoke softly.'", options: ["he", "spoke", "softly", "soft"], correctIndex: 2, level: 11 },
  { id: 'd71', subject: 'english', question: "Which is a proper noun?", options: ["city", "Amazon River", "dog", "happiness"], correctIndex: 1, level: 11 },
  { id: 'd72', subject: 'english', question: "What is the root word of 'unhappiness'?", options: ["happy", "happiness", "un", "ness"], correctIndex: 1, level: 11 },
  { id: 'd73', subject: 'english', question: "Choose the synonym for 'reluctant'.", options: ["eager", "hesitant", "happy", "sure"], correctIndex: 1, level: 11 },
  { id: 'd74', subject: 'english', question: "What type of text is a recipe?", options: ["narrative", "procedural", "poem", "drama"], correctIndex: 1, level: 11 },
  { id: 'd75', subject: 'english', question: "Which word is spelled correctly?", options: ["seperate", "separate", "seprate", "separete"], correctIndex: 1, level: 11 },
  { id: 'd76', subject: 'english', question: "'It's' is a contraction of:", options: ["it is", "its", "it was", "it has"], correctIndex: 0, level: 11 },
  { id: 'd77', subject: 'english', question: "What does 'candid' mean?", options: ["honest", "shy", "loud", "fake"], correctIndex: 0, level: 11 },
  { id: 'd78', subject: 'english', question: "Identify the conjunction: 'I wanted to go but I was tired.'", options: ["I", "wanted", "but", "tired"], correctIndex: 2, level: 11 },
  { id: 'd79', subject: 'english', question: "Which is a fragment?", options: ["She ran.", "Because it was raining.", "He left early.", "They laughed."], correctIndex: 1, level: 11 },
  { id: 'd80', subject: 'english', question: "What is the superlative of 'good'?", options: ["gooder", "better", "best", "goodest"], correctIndex: 2, level: 11 },
  { id: 'd81', subject: 'english', question: "Choose the correct article: '___ apple a day.'", options: ["A", "An", "The", "No article"], correctIndex: 1, level: 11 },
  { id: 'd82', subject: 'english', question: "What does 'versatile' mean?", options: ["rigid", "adaptable", "heavy", "slow"], correctIndex: 1, level: 11 },
  { id: 'd83', subject: 'english', question: "Which sentence is passive voice?", options: ["The cat ate the fish.", "The fish was eaten by the cat.", "The cat is eating."], correctIndex: 1, level: 11 },
  { id: 'd84', subject: 'science', question: "What is the chemical symbol for water?", options: ["H2O", "CO2", "O2", "NaCl"], correctIndex: 0, level: 11 },
  { id: 'd85', subject: 'science', question: "How many planets are in our solar system?", options: ["7", "8", "9", "10"], correctIndex: 1, level: 11 },
  { id: 'd86', subject: 'science', question: "What gas do plants absorb for photosynthesis?", options: ["oxygen", "carbon dioxide", "nitrogen", "helium"], correctIndex: 1, level: 11 },
  { id: 'd87', subject: 'science', question: "The human heart has how many chambers?", options: ["2", "3", "4", "5"], correctIndex: 2, level: 11 },
  { id: 'd88', subject: 'science', question: "What is the powerhouse of the cell?", options: ["nucleus", "mitochondria", "ribosome", "membrane"], correctIndex: 1, level: 11 },
  { id: 'd89', subject: 'science', question: "Which planet is known as the Red Planet?", options: ["Venus", "Mars", "Jupiter", "Mercury"], correctIndex: 1, level: 11 },
  { id: 'd90', subject: 'science', question: "What force keeps us on the ground?", options: ["magnetism", "gravity", "friction", "inertia"], correctIndex: 1, level: 11 },
  { id: 'd91', subject: 'science', question: "The speed of light is approximately:", options: ["300 km/s", "300,000 km/s", "3,000 km/s", "30,000 km/s"], correctIndex: 1, level: 11 },
  { id: 'd92', subject: 'science', question: "What is the atomic number of hydrogen?", options: ["1", "2", "3", "0"], correctIndex: 0, level: 11 },
  { id: 'd93', subject: 'science', question: "Which blood cells fight infection?", options: ["red", "white", "platelets", "plasma"], correctIndex: 1, level: 11 },
  { id: 'd94', subject: 'science', question: "What is the boiling point of water at sea level (C)?", options: ["90", "100", "110", "120"], correctIndex: 1, level: 11 },
  { id: 'd95', subject: 'science', question: "DNA stands for:", options: ["Deoxyribonucleic acid", "Dinucleic acid", "Dual nucleic acid", "None"], correctIndex: 0, level: 11 },
  { id: 'd96', subject: 'science', question: "What type of energy is stored in a battery?", options: ["kinetic", "chemical", "thermal", "sound"], correctIndex: 1, level: 11 },
  { id: 'd97', subject: 'science', question: "The Earth's atmosphere is mostly:", options: ["oxygen", "nitrogen", "carbon dioxide", "argon"], correctIndex: 1, level: 11 },
  { id: 'd98', subject: 'science', question: "Which organ filters blood in the body?", options: ["liver", "kidney", "lung", "heart"], correctIndex: 1, level: 11 },
  { id: 'd99', subject: 'science', question: "What is the closest star to Earth?", options: ["Sirius", "Sun", "Proxima", "Vega"], correctIndex: 1, level: 11 },
  { id: 'd100', subject: 'science', question: "Acids have a pH:", options: ["above 7", "below 7", "of 7", "above 14"], correctIndex: 1, level: 11 },
  { id: 'd101', subject: 'science', question: "What is the hardest natural substance?", options: ["gold", "diamond", "iron", "quartz"], correctIndex: 1, level: 11 },
  { id: 'd102', subject: 'science', question: "Sound travels fastest through:", options: ["vacuum", "solid", "gas", "liquid"], correctIndex: 1, level: 11 },
  { id: 'd103', subject: 'science', question: "Which vitamin do we get from sunlight?", options: ["A", "B", "C", "D"], correctIndex: 3, level: 11 },
  { id: 'd104', subject: 'science', question: "What is the center of an atom called?", options: ["electron", "nucleus", "proton", "neutron"], correctIndex: 1, level: 11 },
  { id: 'd105', subject: 'science', question: "How many bones are in the adult human body?", options: ["206", "201", "210", "196"], correctIndex: 0, level: 11 },
  { id: 'd106', subject: 'science', question: "What causes tides on Earth?", options: ["wind", "moon's gravity", "sunspots", "rotation"], correctIndex: 1, level: 11 },
  { id: 'd107', subject: 'science', question: "Which gas is most abundant in the atmosphere?", options: ["Oxygen", "Nitrogen", "Hydrogen", "Helium"], correctIndex: 1, level: 11 },
  { id: 'd108', subject: 'science', question: "What is the study of stars called?", options: ["geology", "astronomy", "biology", "chemistry"], correctIndex: 1, level: 11 },
  { id: 'd109', subject: 'science', question: "Electric current is measured in:", options: ["volts", "amperes", "watts", "ohms"], correctIndex: 1, level: 11 },
  { id: 'd110', subject: 'science', question: "Which part of the plant conducts photosynthesis?", options: ["root", "leaf", "stem", "flower"], correctIndex: 1, level: 11 },
  { id: 'd111', subject: 'science', question: "What is the chemical symbol for gold?", options: ["Go", "Gd", "Au", "Ag"], correctIndex: 2, level: 11 },
  { id: 'd112', subject: 'science', question: "A thermometer measures:", options: ["pressure", "temperature", "volume", "mass"], correctIndex: 1, level: 11 },
  { id: 'd113', subject: 'science', question: "What is the largest organ in the human body?", options: ["heart", "skin", "liver", "brain"], correctIndex: 1, level: 11 },
  { id: 'd114', subject: 'science', question: "Which animal is a mammal?", options: ["shark", "dolphin", "eagle", "frog"], correctIndex: 1, level: 11 },
  { id: 'd115', subject: 'science', question: "What is the freezing point of water (C)?", options: ["0", "10", "-10", "32"], correctIndex: 0, level: 11 },
  { id: 'd116', subject: 'science', question: "What type of rock is formed by cooling lava?", options: ["sedimentary", "igneous", "metamorphic", "none"], correctIndex: 1, level: 11 },
  { id: 'd117', subject: 'science', question: "The ozone layer protects us from:", options: ["sound", "UV radiation", "rain", "wind"], correctIndex: 1, level: 11 },
  { id: 'd118', subject: 'science', question: "What is the smallest unit of matter?", options: ["cell", "atom", "molecule", "electron"], correctIndex: 1, level: 11 },
  { id: 'd119', subject: 'science', question: "Which of these is a renewable energy source?", options: ["coal", "solar", "oil", "natural gas"], correctIndex: 1, level: 11 },
  { id: 'd120', subject: 'science', question: "What does the respiratory system primarily exchange?", options: ["food", "oxygen and CO2", "blood", "water"], correctIndex: 1, level: 11 },
  { id: 'd121', subject: 'science', question: "What is the chemical symbol for sodium?", options: ["So", "Na", "Sd", "Sa"], correctIndex: 1, level: 11 },
  { id: 'd122', subject: 'science', question: "Which sense is associated with the nose?", options: ["taste", "smell", "touch", "sight"], correctIndex: 1, level: 11 },
  { id: 'd123', subject: 'science', question: "What is the process of a liquid turning to gas?", options: ["freezing", "evaporation", "condensation", "melting"], correctIndex: 1, level: 11 },
  { id: 'd124', subject: 'science', question: "How many chambers does a fish heart have?", options: ["2", "3", "4", "1"], correctIndex: 0, level: 11 },
  { id: 'd125', subject: 'social_studies', question: "In which year did World War II end?", options: ["1943", "1945", "1950", "1939"], correctIndex: 1, level: 11 },
  { id: 'd126', subject: 'social_studies', question: "Who was the first President of the United States?", options: ["Lincoln", "Washington", "Jefferson", "Adams"], correctIndex: 1, level: 11 },
  { id: 'd127', subject: 'social_studies', question: "The Declaration of Independence was signed in:", options: ["1776", "1789", "1812", "1620"], correctIndex: 0, level: 11 },
  { id: 'd128', subject: 'social_studies', question: "Which document begins 'We the People'?", options: ["Bill of Rights", "Constitution", "Emancipation", "Articles"], correctIndex: 1, level: 11 },
  { id: 'd129', subject: 'social_studies', question: "What are the three branches of U.S. government?", options: ["exec, leg, jud", "pres, sen, house", "army, navy, air", "none"], correctIndex: 0, level: 11 },
  { id: 'd130', subject: 'social_studies', question: "Who wrote the Gettysburg Address?", options: ["Washington", "Lincoln", "Kennedy", "Roosevelt"], correctIndex: 1, level: 11 },
  { id: 'd131', subject: 'social_studies', question: "The Civil War was fought mainly over:", options: ["taxes", "slavery", "land", "trade"], correctIndex: 1, level: 11 },
  { id: 'd132', subject: 'social_studies', question: "Which amendment gave women the right to vote?", options: ["15th", "19th", "13th", "21st"], correctIndex: 1, level: 11 },
  { id: 'd133', subject: 'social_studies', question: "What is the capital of the United States?", options: ["New York", "Washington D.C.", "Chicago", "Boston"], correctIndex: 1, level: 11 },
  { id: 'd134', subject: 'social_studies', question: "How many stars are on the U.S. flag?", options: ["48", "50", "52", "51"], correctIndex: 1, level: 11 },
  { id: 'd135', subject: 'social_studies', question: "Who was the primary author of the Declaration of Independence?", options: ["Adams", "Jefferson", "Franklin", "Madison"], correctIndex: 1, level: 11 },
  { id: 'd136', subject: 'social_studies', question: "The Great Depression began in:", options: ["1919", "1929", "1939", "1945"], correctIndex: 1, level: 11 },
  { id: 'd137', subject: 'social_studies', question: "Which ocean borders the U.S. east coast?", options: ["Pacific", "Atlantic", "Indian", "Arctic"], correctIndex: 1, level: 11 },
  { id: 'd138', subject: 'social_studies', question: "What is the supreme law of the land?", options: ["President", "Constitution", "Congress", "Supreme Court"], correctIndex: 1, level: 11 },
  { id: 'd139', subject: 'social_studies', question: "Who is the head of the executive branch?", options: ["Chief Justice", "President", "Speaker", "Senate"], correctIndex: 1, level: 11 },
  { id: 'd140', subject: 'social_studies', question: "The Emancipation Proclamation was issued by:", options: ["Lincoln", "Washington", "Grant", "Lee"], correctIndex: 0, level: 11 },
  { id: 'd141', subject: 'social_studies', question: "Which war was fought in the 1960s in Vietnam?", options: ["WWI", "Vietnam War", "Korean", "Cold"], correctIndex: 1, level: 11 },
  { id: 'd142', subject: 'social_studies', question: "What is the legislative branch made of?", options: ["Senate & House", "Court", "President", "Governor"], correctIndex: 0, level: 11 },
  { id: 'd143', subject: 'social_studies', question: "Who has the power to declare war?", options: ["President", "Congress", "Supreme Court", "States"], correctIndex: 1, level: 11 },
  { id: 'd144', subject: 'social_studies', question: "The U.S. bought Louisiana from which country?", options: ["Britain", "France", "Spain", "Mexico"], correctIndex: 1, level: 11 },
  { id: 'd145', subject: 'social_studies', question: "What year did the U.S. land on the moon?", options: ["1965", "1969", "1972", "1958"], correctIndex: 1, level: 11 },
  { id: 'd146', subject: 'social_studies', question: "Which is NOT a U.S. territory?", options: ["Puerto Rico", "Guam", "Texas", "Virgin Islands"], correctIndex: 2, level: 11 },
  { id: 'd147', subject: 'social_studies', question: "The Bill of Rights has how many amendments?", options: ["10", "12", "15", "8"], correctIndex: 0, level: 11 },
  { id: 'd148', subject: 'social_studies', question: "Who was President during the Civil War?", options: ["Lincoln", "Washington", "Jackson", "Hoover"], correctIndex: 0, level: 11 },
  { id: 'd149', subject: 'social_studies', question: "What is the economic system of the U.S.?", options: ["communism", "capitalism", "socialism", "feudalism"], correctIndex: 1, level: 11 },
  { id: 'd150', subject: 'social_studies', question: "The Magna Carta influenced:", options: ["U.S. Constitution", "French food", "British navy", "none"], correctIndex: 0, level: 11 },
  { id: 'd151', subject: 'social_studies', question: "Which state was the first to join the Union?", options: ["Texas", "Delaware", "California", "Florida"], correctIndex: 1, level: 11 },
  { id: 'd152', subject: 'social_studies', question: "What is the judicial branch's main role?", options: ["make laws", "interpret laws", "enforce laws", "tax"], correctIndex: 1, level: 11 },
  { id: 'd153', subject: 'social_studies', question: "The Cold War was mainly between the U.S. and:", options: ["Britain", "Soviet Union", "France", "China"], correctIndex: 1, level: 11 },
  { id: 'd154', subject: 'social_studies', question: "Who elects U.S. Senators?", options: ["governors", "voters", "President", "mayors"], correctIndex: 1, level: 11 },
  { id: 'd155', subject: 'social_studies', question: "What does 'Habeas Corpus' protect?", options: ["free speech", "against unlawful detention", "property", "vote"], correctIndex: 1, level: 11 },
  { id: 'd156', subject: 'social_studies', question: "The Industrial Revolution began in which country?", options: ["USA", "Britain", "Germany", "France"], correctIndex: 1, level: 11 },
  { id: 'd157', subject: 'social_studies', question: "Which amendment protects free speech?", options: ["1st", "2nd", "4th", "10th"], correctIndex: 0, level: 11 },
  { id: 'd158', subject: 'social_studies', question: "What is the minimum voting age in the U.S.?", options: ["18", "21", "16", "25"], correctIndex: 0, level: 11 },
  { id: 'd159', subject: 'social_studies', question: "Who is the Commander-in-Chief of the military?", options: ["Senate", "President", "General", "Chief Justice"], correctIndex: 1, level: 11 },
  { id: 'd160', subject: 'social_studies', question: "The Titanic sank in which year?", options: ["1905", "1912", "1920", "1898"], correctIndex: 1, level: 11 },
  { id: 'd161', subject: 'social_studies', question: "Which ancient civilization built the pyramids?", options: ["Roman", "Egyptian", "Greek", "Chinese"], correctIndex: 1, level: 11 },
  { id: 'd162', subject: 'social_studies', question: "What is the longest river in the U.S.?", options: ["Colorado", "Mississippi", "Hudson", "Ohio"], correctIndex: 1, level: 11 },
  { id: 'd163', subject: 'social_studies', question: "The United Nations was founded in:", options: ["1918", "1945", "1960", "1939"], correctIndex: 1, level: 11 },
  { id: 'd164', subject: 'social_studies', question: "Which President issued the New Deal?", options: ["Hoover", "Roosevelt", "Truman", "Eisenhower"], correctIndex: 1, level: 11 },
  { id: 'd165', subject: 'social_studies', question: "What is the capital of Alabama?", options: ["Birmingham", "Montgomery", "Mobile", "Huntsville"], correctIndex: 1, level: 11 },
  { id: 'd166', subject: 'social_studies', question: "The 13 original colonies were under which empire?", options: ["French", "British", "Spanish", "Dutch"], correctIndex: 1, level: 11 },
  { id: 'd167', subject: 'life_skills', question: "What is the purpose of a budget?", options: ["track income and spending", "avoid taxes", "save nothing", "spend more"], correctIndex: 0, level: 11 },
  { id: 'd168', subject: 'life_skills', question: "A credit score measures:", options: ["income", "creditworthiness", "age", "education"], correctIndex: 1, level: 11 },
  { id: 'd169', subject: 'life_skills', question: "What does APR stand for on a loan?", options: ["Annual Percentage Rate", "Auto Payment Rate", "Added Price", "None"], correctIndex: 0, level: 11 },
  { id: 'd170', subject: 'life_skills', question: "Why is an emergency fund important?", options: ["for vacations", "for unexpected expenses", "to buy cars", "none"], correctIndex: 1, level: 11 },
  { id: 'd171', subject: 'life_skills', question: "What is a W-2 form used for?", options: ["voting", "reporting wages/taxes", "drivers license", "school"], correctIndex: 1, level: 11 },
  { id: 'd172', subject: 'life_skills', question: "Which is a fixed expense?", options: ["groceries", "rent", "entertainment", "gas"], correctIndex: 1, level: 11 },
  { id: 'd173', subject: 'life_skills', question: "What should you do before signing a contract?", options: ["read it", "ignore it", "sign fast", "none"], correctIndex: 0, level: 11 },
  { id: 'd174', subject: 'life_skills', question: "What is the benefit of compound interest?", options: ["loses money", "earns interest on interest", "no growth", "none"], correctIndex: 1, level: 11 },
  { id: 'd175', subject: 'life_skills', question: "How often should you check your bank statements?", options: ["never", "regularly", "yearly", "only at tax time"], correctIndex: 1, level: 11 },
  { id: 'd176', subject: 'life_skills', question: "What is identity theft?", options: ["losing ID", "someone using your info fraudulently", "forgetting password", "none"], correctIndex: 1, level: 11 },
  { id: 'd177', subject: 'life_skills', question: "A good resume should include:", options: ["lies", "relevant skills/experience", "fake degrees", "nothing"], correctIndex: 1, level: 11 },
  { id: 'd178', subject: 'life_skills', question: "What is net pay?", options: ["gross pay", "take-home after deductions", "bonus", "overtime"], correctIndex: 1, level: 11 },
  { id: 'd179', subject: 'life_skills', question: "Why is punctuality important at work?", options: ["shows reliability", "wastes time", "optional", "none"], correctIndex: 0, level: 11 },
  { id: 'd180', subject: 'life_skills', question: "What is a deductible in insurance?", options: ["monthly premium", "amount paid before coverage", "total cost", "none"], correctIndex: 1, level: 11 },
  { id: 'd181', subject: 'life_skills', question: "Which is a healthy eating habit?", options: ["skip meals", "balanced diet", "only fast food", "no water"], correctIndex: 1, level: 11 },
  { id: 'd182', subject: 'life_skills', question: "How many hours of sleep is recommended for adults?", options: ["3-4", "7-9", "12", "2"], correctIndex: 1, level: 11 },
  { id: 'd183', subject: 'life_skills', question: "What should you do in a fire?", options: ["use elevator", "evacuate via stairs", "hide", "call only"], correctIndex: 1, level: 11 },
  { id: 'd184', subject: 'life_skills', question: "What is the purpose of car insurance?", options: ["optional", "financial protection", "cheaper gas", "none"], correctIndex: 1, level: 11 },
  { id: 'd185', subject: 'life_skills', question: "A 401(k) is a:", options: ["bank account", "retirement savings plan", "credit card", "loan"], correctIndex: 1, level: 11 },
  { id: 'd186', subject: 'life_skills', question: "What is the first step in job searching?", options: ["apply randomly", "identify skills/interests", "quit current job", "none"], correctIndex: 1, level: 11 },
  { id: 'd187', subject: 'life_skills', question: "Why is it important to vote?", options: ["mandatory", "voice in government", "wastes time", "none"], correctIndex: 1, level: 11 },
  { id: 'd188', subject: 'life_skills', question: "What does 'due diligence' mean?", options: ["carelessness", "reasonable care/research", "speed", "none"], correctIndex: 1, level: 11 },
  { id: 'd189', subject: 'life_skills', question: "How can you reduce debt?", options: ["pay only minimum", "budget and pay extra", "ignore it", "borrow more"], correctIndex: 1, level: 11 },
  { id: 'd190', subject: 'life_skills', question: "What is a lease?", options: ["a loan", "a rental agreement", "a purchase", "none"], correctIndex: 1, level: 11 },
  { id: 'd191', subject: 'life_skills', question: "Which is a renewable resource?", options: ["coal", "solar", "oil", "gas"], correctIndex: 1, level: 11 },
  { id: 'd192', subject: 'life_skills', question: "What is the benefit of recycling?", options: ["wastes time", "conserves resources", "costs more", "none"], correctIndex: 1, level: 11 },
  { id: 'd193', subject: 'life_skills', question: "What should a first-aid kit contain?", options: ["nothing", "bandages/antiseptic", "toys", "food"], correctIndex: 1, level: 11 },
  { id: 'd194', subject: 'life_skills', question: "Why should you compare prices before buying?", options: ["wasteful", "get best value", "slow", "none"], correctIndex: 1, level: 11 },
  { id: 'd195', subject: 'life_skills', question: "What is the purpose of a cover letter?", options: ["replace resume", "introduce yourself to employer", "fake info", "none"], correctIndex: 1, level: 11 },
  { id: 'd196', subject: 'life_skills', question: "What does 'networking' mean in careers?", options: ["social media only", "building professional relationships", "gaming", "none"], correctIndex: 1, level: 11 },
  { id: 'd197', subject: 'life_skills', question: "How do you handle workplace conflict?", options: ["yell", "communicate respectfully", "quit", "ignore"], correctIndex: 1, level: 11 },
  { id: 'd198', subject: 'life_skills', question: "What is the benefit of education/training?", options: ["none", "better opportunities", "waste", "debt only"], correctIndex: 1, level: 11 },
  { id: 'd199', subject: 'life_skills', question: "Why keep important documents safe?", options: ["unnecessary", "prevent loss/theft", "clutter", "none"], correctIndex: 1, level: 11 },
  { id: 'd200', subject: 'life_skills', question: "What is a money order?", options: ["a loan", "prepaid payment method", "credit card", "none"], correctIndex: 1, level: 11 },
  { id: 'd201', subject: 'life_skills', question: "How can you build credit?", options: ["ignore bills", "pay on time", "max out cards", "none"], correctIndex: 1, level: 11 },
  { id: 'd202', subject: 'life_skills', question: "What is the purpose of insurance?", options: ["optional", "risk protection", "cheaper", "none"], correctIndex: 1, level: 11 },
  { id: 'd203', subject: 'life_skills', question: "Why is a clean workspace beneficial?", options: ["no reason", "productivity/safety", "messy is fine", "none"], correctIndex: 1, level: 11 },
  { id: 'd204', subject: 'life_skills', question: "What is the danger of payday loans?", options: ["low cost", "very high interest", "safe", "none"], correctIndex: 1, level: 11 },
  { id: 'd205', subject: 'life_skills', question: "What should you verify before a job offer?", options: ["nothing", "legitimacy/terms", "trust all", "none"], correctIndex: 1, level: 11 },
  { id: 'd206', subject: 'life_skills', question: "How do you report income to the IRS?", options: ["never", "file tax return", "ignore", "call"], correctIndex: 1, level: 11 },
  { id: 'd207', subject: 'life_skills', question: "What is the value of saving regularly?", options: ["none", "financial security", "debt", "waste"], correctIndex: 1, level: 11 },
  { id: 'd208', subject: 'life_skills', question: "Why read product reviews?", options: ["waste", "informed choice", "slow", "none"], correctIndex: 1, level: 11 },
  { id: 'd209', subject: 'life_skills', question: "What is a healthy response to stress?", options: ["ignore", "exercise/talk/balance", "yell", "substance"], correctIndex: 1, level: 11 },
]

export const DIPLOMA_PASS_THRESHOLD = 0.7 // 70% to pass
