with open(r'C:\Users\1990j\coverschool\src\lib\curriculum.ts') as f:
    content = f.read()

# Find the broken line and section boundaries
broken = "{ id: 'K-SP-W8-1', q: 'Which words al"
g1_start = content.find("// ====================== 1ST GRADE ======================")
idx = content.find(broken)

new_tail = (
    "{ id: 'K-SP-W8-1', q: 'Which words all end with \"og\"?', type: 'mc', options: ['dog, log, frog', 'bat, cat, hat', 'big, pig, fig'], answer: 0 },\n"
    "          { id: 'K-SP-W8-2', q: 'What sound do you hear at the end of \"dog\"?', type: 'mc', options: ['og', 'at', 'ig'], answer: 0 },\n"
    "          { id: 'K-SP-W8-3', q: 'Which word belongs in the \"og\" family?', type: 'mc', options: ['frog', 'cat', 'sun'], answer: 0 },\n"
    "          { id: 'K-SP-W8-4', q: 'Which word rhymes with \"log\"?', type: 'mc', options: ['frog', 'cat', 'sun'], answer: 0 },\n"
    "        ] },\n"
    "        { title: 'Fun with Family Words', summary: \"Lets say word families together! Bat, cat, hat! Dog, log, frog!\", weekTest: [\n"
    "          { id: 'K-SP-W9-1', q: 'Which word belongs to the \"at\" family?', type: 'mc', options: ['bat', 'dog', 'sun'], answer: 0 },\n"
    "          { id: 'K-SP-W9-2', q: 'Which word belongs to the \"og\" family?', type: 'mc', options: ['frog', 'hat', 'big'], answer: 0 },\n"
    "          { id: 'K-SP-W9-3', q: 'Does \"cat\" end with \"at\" or \"og\"?', type: 'mc', options: ['at', 'og', 'neither'], answer: 0 },\n"
    "          { id: 'K-SP-W9-4', q: 'Does \"dog\" end with \"at\" or \"og\"?', type: 'mc', options: ['at', 'og', 'neither'], answer: 1 },\n"
    "        ] },\n"
    "      ], questions: [\n"
    "        { id: 'K-SP-Q3-1', q: 'Which ending sound do bat, cat, hat share?', type: 'mc', options: ['at', 'og', 'ig'], answer: 0 },\n"
    "        { id: 'K-SP-Q3-2', q: 'Which ending sound do dog, log, frog share?', type: 'mc', options: ['at', 'og', 'ig'], answer: 1 },\n"
    "      ]},\n"
    "      { name: 'Q4 - Review', lessons: [\n"
    "        { title: 'Words I Know', summary: 'Look at all the words we learned! Can you find \"the\"? You know so many words!' },\n"
    "        { title: 'Letters I Know', summary: 'We learned letters A, B, C, M, S! Can you point to the letter A?' },\n"
    "        { title: 'Let Us Read Together', summary: \"Let's look at a book together! Point to a word you know!\" },\n"
    "      ], questions: [\n"
    "        { id: 'K-SP-Q4-1', q: 'Point to the word \"the\". Which one is \"the\"?', type: 'mc', options: ['the', 'cat', 'dog'], answer: 0 },\n"
    "        { id: 'K-SP-Q4-2', q: 'Which letter makes the \"buh\" sound?', type: 'mc', options: ['B', 'A', 'C'], answer: 0 },\n"
    "      ]},\n"
    "    ]},\n"
    "    { name: 'Science', units: [\n"
    "      { name: 'Q1 - Gods World', lessons: [\n"
    "        { title: 'Day and Night', summary: 'God made the sun for daytime and the moon for nighttime.' },\n"
    "        { title: 'The Sun and Moon', summary: 'The sun is bright and hot. The moon shines at night.' },\n"
    "        { title: 'Weather', summary: 'Sometimes it is sunny. Sometimes it rains. What is the weather today?' },\n"
    "      ], questions: [\n"
    "        { id: 'K-SC-Q1-1', q: 'When the sun is out, it is ___', type: 'mc', options: ['daytime', 'nighttime', 'bedtime'], answer: 0 },\n"
    "        { id: 'K-SC-Q1-2', q: 'The sun gives us ___', type: 'mc', options: ['light', 'rain', 'snow'], answer: 0 },\n"
    "      ]},\n"
    "      { name: 'Q2 - Animals', lessons: [\n"
    "        { title: 'Farm Animals', summary: 'A cow says moo! A pig says oink! A chicken says cluck!' },\n"
    "        { title: 'Pets', summary: 'A dog is a pet. A cat is a pet. Do you have a pet?' },\n"
    "        { title: 'Animal Babies', summary: 'A baby dog is a puppy. A baby cat is a kitten.' },\n"
    "      ], questions: [\n"
    "        { id: 'K-SC-Q2-1', q: 'Which animal says \"moo\"?', type: 'mc', options: ['cow', 'dog', 'chicken'], answer: 0 },\n"
    "        { id: 'K-SC-Q2-2', q: 'Which animal is a pet?', type: 'mc', options: ['dog', 'lion', 'bear'], answer: 0 },\n"
    "      ]},\n"
    "      { name: 'Q3 - My Body', lessons: [\n"
    "        { title: 'My Body Parts', summary: 'You have eyes to see, ears to hear, and hands to touch!' },\n"
    "        { title: 'My Five Senses', summary: 'We see with our eyes. We hear with our ears. We smell with our nose!' },\n"
    "        { title: 'Staying Healthy', summary: 'We wash our hands. We brush our teeth. We eat good food!' },\n"
    "      ], questions: [\n"
    "        { id: 'K-SC-Q3-1', q: 'We see with our ___', type: 'mc', options: ['eyes', 'ears', 'nose'], answer: 0 },\n"
    "        { id: 'K-SC-Q3-2', q: 'We hear with our ___', type: 'mc', options: ['eyes', 'ears', 'nose'], answer: 1 },\n"
    "      ]},\n"
    "      { name: 'Q4 - Seasons', lessons: [\n"
    "        { title: 'Four Seasons', summary: 'God made four seasons! Spring, summer, fall, winter.' },\n"
    "        { title: 'Summer and Winter', summary: 'Summer is hot! We wear shorts. Winter is cold! We wear coats.' },\n"
    "        { title: 'Spring and Fall', summary: 'Spring has flowers! Fall has colorful leaves!' },\n"
    "      ], questions: [\n"
    "        { id: 'K-SC-Q4-1', q: 'In summer the weather is ___', type: 'mc', options: ['hot', 'cold', 'snowy'], answer: 0 },\n"
    "        { id: 'K-SC-Q4-2', q: 'In winter the weather is ___', type: 'mc', options: ['hot', 'cold', 'rainy'], answer: 1 },\n"
    "      ]},\n"
    "    ]},\n"
    "    { name: 'History & Geography', units: [\n"
    "      { name: 'Q1 - My Family', lessons: [\n"
    "        { title: 'People in My Family', summary: 'Every family is special! A mom and dad. Who is in your family?' },\n"
    "        { title: 'My Home', summary: 'You live in a home with a kitchen, bedroom, and living room.' },\n"
    "        { title: 'Taking Care of Each Other', summary: 'Families take care of each other! You can help by picking up your toys!' },\n"
    "      ], questions: [\n"
    "        { id: 'K-H-Q1-1', q: 'Who takes care of you at home?', type: 'mc', options: ['Mom and Dad', 'A stranger', 'No one'], answer: 0 },\n"
    "        { id: 'K-H-Q1-2', q: 'You live in a ___', type: 'mc', options: ['home', 'store', 'school'], answer: 0 },\n"
    "      ]},\n"
    "      { name: 'Q2 - Community Helpers', lessons: [\n"
    "        { title: 'Firefighters', summary: 'Firefighters put out fires and keep us safe!' },\n"
    "        { title: 'Doctors and Teachers', summary: 'A doctor helps you when you are sick. A teacher helps you learn!' },\n"
    "        { title: 'Helpers in Our Town', summary: 'The mailman brings letters. The farmer grows our food.' },\n"
    "      ], questions: [\n"
    "        { id: 'K-H-Q2-1', q: 'Who puts out fires?', type: 'mc', options: ['firefighter', 'teacher', 'baker'], answer: 0 },\n"
    "        { id: 'K-H-Q2-2', q: 'Who helps you when you are sick?', type: 'mc', options: ['doctor', 'firefighter', 'mailman'], answer: 0 },\n"
    "      ]},\n"
    "      { name: 'Q3 - Our World', lessons: [\n"
    "        { title: 'Earth Is Round', summary: 'Our Earth is round like a ball! We live on Earth.' },\n"
    "        { title: 'Maps Show Places', summary: 'A map shows where places are in our town.' },\n"
    "        { title: 'Where Do We Live?', summary: 'We live in a town with houses, stores, and schools.' },\n"
    "      ], questions: [\n"
    "        { id: 'K-H-Q3-1', q: 'Earth is shaped like a ___', type: 'mc', options: ['ball', 'box', 'plate'], answer: 0 },\n"
    "        { id: 'K-H-Q3-2', q: 'A map shows ___', type: 'mc', options: ['places', 'food', 'toys'], answer: 0 },\n"
    "      ]},\n"
    "      { name: 'Q4 - Holidays', lessons: [\n"
    "        { title: 'Christmas', summary: 'Christmas is when we celebrate Jesus birthday! We give gifts.' },\n"
    "        { title: 'Thanksgiving', summary: 'On Thanksgiving we say thank you for all we have!' },\n"
    "        { title: 'My Birthday', summary: 'Your birthday is the day you were born! We celebrate with cake!' },\n"
    "      ], questions: [\n"
    "        { id: 'K-H-Q4-1', q: 'At Christmas we celebrate ___ birthday', type: 'mc', options: ['Jesus', 'yours', 'no ones'], answer: 0 },\n"
    "        { id: 'K-H-Q4-2', q: 'On Thanksgiving we say ___', type: 'mc', options: ['thank you', 'happy birthday', 'goodnight'], answer: 0 },\n"
    "      ]},\n"
    "    ]},\n"
    "    { name: 'Bible & Character', units: [\n"
    "      { name: 'Q1 - God Made Me', lessons: [\n"
    "        { title: 'I Am Special', summary: 'God made you and you are special! Look in the mirror and smile!' },\n"
    "        { title: 'God Made the World', summary: 'God made the sun, moon, stars, trees, and animals!' },\n"
    "        { title: 'Thank You God', summary: \"Let's say thank you to God for our family, our home, and our toys!\" },\n"
    "      ], questions: [\n"
    "        { id: 'K-B-Q1-1', q: 'Who made you?', type: 'mc', options: ['God', 'a robot', 'no one'], answer: 0 },\n"
    "        { id: 'K-B-Q1-2', q: 'Who made the sun and stars?', type: 'mc', options: ['God', 'a man', 'a bird'], answer: 0 },\n"
    "      ]},\n"
    "      { name: 'Q2 - Jesus Loves Me', lessons: [\n"
    "        { title: 'Baby Jesus', summary: 'Baby Jesus was born. God sent Jesus because He loves us!' },\n"
    "        { title: 'Jesus Is My Friend', summary: 'Jesus loves you and is your friend! You can talk to Jesus anytime.' },\n"
    "        { title: 'Jesus Helps Us', summary: 'Jesus helps us when we are sad or scared.' },\n"
    "      ], questions: [\n"
    "        { id: 'K-B-Q2-1', q: 'Jesus loves ___', type: 'mc', options: ['you', 'no one', 'only grown-ups'], answer: 0 },\n"
    "        { id: 'K-B-Q2-2', q: 'Jesus is our ___', type: 'mc', options: ['friend', 'enemy', 'stranger'], answer: 0 },\n"
    "      ]},\n"
    "      { name: 'Q3 - Being Kind', lessons: [\n"
    "        { title: 'Share with Others', summary: 'Sharing makes everyone happy! Can you share your toy?' },\n"
    "        { title: 'Use Kind Words', summary: 'Please and thank you are kind words! Can you say please?' },\n"
    "        { title: 'Be a Good Friend', summary: 'A good friend shares, is kind, and helps others!' },\n"
    "      ], questions: [\n"
    "        { id: 'K-B-Q3-1', q: 'When someone gives you something, say ___', type: 'mc', options: ['thank you', 'no', 'go away'], answer: 0 },\n"
    "        { id: 'K-B-Q3-2', q: 'A good friend is ___', type: 'mc', options: ['kind', 'mean', 'loud'], answer: 0 },\n"
    "      ]},\n"
    "      { name: 'Q4 - Thankful Hearts', lessons: [\n"
    "        { title: 'Thank You for Food', summary: 'Before we eat, we thank God for this food!' },\n"
    "        { title: 'Thank You for Family', summary: 'God gave you your family who love you!' },\n"
    "        { title: 'I Am Thankful', summary: \"What are you thankful for? Let's thank God for it!\" },\n"
    "      ], questions: [\n"
    "        { id: 'K-B-Q4-1', q: 'Before we eat, we thank ___', type: 'mc', options: ['God', 'the food', 'the table'], answer: 0 },\n"
    "        { id: 'K-B-Q4-2', q: 'We say thank you for our ___', type: 'mc', options: ['family', 'garbage', 'nothing'], answer: 0 },\n"
    "      ]},\n"
    "    ]},\n"
    "  ])\n\n"
)

content = content[:idx] + new_tail + content[g1_start:]

with open(r'C:\Users\1990j\coverschool\src\lib\curriculum.ts', 'w') as f:
    f.write(content)

import re
short = len(re.findall(r"type: 'short'", content))
activity = len(re.findall(r"type: 'activity'", content))
print(f"Fixed! Short: {short}, Activity: {activity}")
print(f"Total K question references: {len(re.findall(r'id: .K-', content))}")
